### ISSUE TITLE
This repository is marked for deletion!

### ISSUE THREAD

**Issue by bkimminich** [OWASP/Top10#1]
Dear repository owner, 

this repository seems either empty or abandoned on GitHub. In order to clean up the https://github.com/owasp organization, please acknowledge or veto the deletion of this repository.

No response will be interpreted as evidence for the obsolescence of this repository and it will be deleted at some point in time.

Thank you for helping to clean up the OWASP GitHub org!

Cheers, 
Björn (@bkimminich)

**Comment by davewichers** [comment]
I just created this for the 2017 Top 10, that I am working on now. I will be checking stuff in within the month.

Dave

**Comment by bkimminich** [comment]
:ok:

**Comment by bkimminich** [comment]
I just noticed there is another similar project with content already: https://github.com/OWASP/OWASP-Top-10

Is this one the "next generation" or should the content you are planning to put here rather go into the existing repo?

**Comment by davewichers** [comment]
I'm not involved with: https://github.com/OWASP/OWASP-Top-10, and not sure
what it is or what it is for. It looks like the personal project of the 1
or 2 contributors that hasn't been used in 3 years. Its not an official
OWASP Top 10 project repo. Maybe it should go away?

-Dave
