### ISSUE TITLE
Some table content overlaps in the documentation. [2017]

### ISSUE THREAD

**Issue by ruroot** [OWASP/Top10#100]
In pg. 5 and some others, you can clearly see that table content strings overlaps and therefore not readable. 

I have tested on latest firefox and kali's default evince pdf reader and the result is the same.
I hope this issue is not duplicate, I haven't fully checked.

You can see the example below:

![screenshot from 2017-10-02 18-17-35](https://user-images.githubusercontent.com/20649815/31084889-51ad0ab8-a79e-11e7-8698-fd00b5b0eb4c.png)

**Comment by vanderaj** [comment]
We are just using the automated PDF generation from pandoc whilst we create / craft / edit the final text. It's going to be included in a PowerPoint once text is complete. The Markdown is considered canonical until we release RC2 Friday 20th October.
