### ISSUE TITLE
Possibility of Rolling call for data? (Summit Process session, Mon AM1)

### ISSUE THREAD

**Issue by tghosth** [OWASP/Top10#11]
Would it make sense to have an open/rolling call for data?

In this model, companies can submit data in a pre-agreed, specific format when they are able to without waiting for a particular "call for data" window.

A cut-off would need to be defined for each version of the Top 10.

The submission format would need to include a more exact date range for the data to make comparison easier.

**Comment by tghosth** [comment]
This was briefly discussed in this session and I think the consensus was that it would be difficult to manage and take advantage of this.

**Comment by infosecdad** [comment]
Ideally, we could build a model that would be fed in near realtime, but I believe that's a ways off yet. A lot of time and effort is being put into pulling these numbers for us and I don't want to overburden contributors. We are considering different options of how to possibly have at least mid-cycle data updates to look for trends (while not necessarily changing the core Top 10 itself).
