### ISSUE TITLE
TOC(new), +AM(new): Feedback on 2017-RC1: add a table of contents, add a new page '+A What's Next for Application Managers' (was: overall feedback on content)

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#12]
Hi,

I've read all the Top 10-2017 RC and gave a comment if I suggest to change some content. I did not
focus solely on A7 and A10, but they are obviously included in my suggestions. As I was part of the
team that translated the Top 10 -2013 in German, so I've also recapped my remarks I've made when we
were translating that Top 10.

I've compiled all my comments now into the pptx file to see if the changed parts could fit. All
changes are _highlighted by using green font and comments_ (sometimes containing background
information why I'd suggest a change).
I'm sorry, I am not a native speaker, so I hope you can always understand what I mean.

[OWASP Top 10 - 2017 RC1-English_Comments_from_Torsten_20170609.pptx](http://lists.owasp.org/pipermail/owasp-topten/attachments/20170609/b7bd1ba9/attachment-0001.pptx)

There might fit also
  * a table of contents at the beginning (see comment on 'O', we've already added one at
    https://www.owasp.org/images/4/42/OWASP_Top_10_2013_DE_Version_1_0.pdf)
  * a new page '+A(M) What's Next for Application Managers' describing the lifecycle processes to
    tender a software, to implace the application and its components, to maintain them, to change
    it, to retire it while keeping data for post production and finally to delete all data, software
    and components (no comments added about this in the pptx).

I hope it helps for the discussions at the OWASP Summit and compiling the RC2/final document.

Cheers
Torsten (Gigler)
Peposted from Mailing List as requested (http://lists.owasp.org/pipermail/owasp-topten/2017-June/001510.html)

**Comment by sslHello** [comment]
I've opened individual issues #64 .. #79 by the page for all feedback that is in the pptx above (some were updated, too).
Besides the two points above in the text 'There might fit also...'
Cheers 
Torsten (Gigler)

**Comment by vanderaj** [comment]
Written
