### ISSUE TITLE
+D What's next for developers QA

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#126]
QA (we must hear from a majority of project leads saying approved before closing)

- [x] Ready for review?
- [x] Spelling
- [x] Content
- [ ] Issues are modern, deal with apps and API?
- [ ] Recommendations are modern, deal with apps and API?
- [ ] Example scenarios, reference real world breaches? 
- [ ] Can it be any smaller without losing information?
- [x] Links (if any) - OWASP primary sources, stable secondary sources?

**Comment by vanderaj** [comment]
I've QA'd this. I'm happy with the content. Please add your own reviews.

**Comment by vdbaan** [comment]
Please add links to the projects in the other boxes like in the box Application Security Education.

**Comment by vanderaj** [comment]
The slide has old content in it. As I can't edit it outside the PPT, I will try to fix tonight

**Comment by vanderaj** [comment]
This is now addressed in offline editing
