### ISSUE TITLE
+AM What's next for application managers

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#128]
QA (we must hear from a majority of project leads saying approved before closing)

- [x] Ready for review?
- [x] Spelling
- [x] Content
- [ ] Issues are modern, deal with apps and API?
- [ ] Recommendations are modern, deal with apps and API?
- [ ] Example scenarios, reference real world breaches? 
- [ ] Can it be any smaller without losing information?
- [x] Links (if any) - OWASP primary sources, stable secondary sources?

**Comment by vanderaj** [comment]
I've QA'd and refactored this section quite a great deal. @sslHello please review and let me know if this is better or worse.

More references would be good.

**Comment by vdbaan** [comment]
Please add a link to "What's next for Developers"

**Comment by vanderaj** [comment]
Whoops, I screwed the smart art. Gonna have to fix this in the PPTX

**Comment by vanderaj** [comment]
This is done
