### ISSUE TITLE
RISK: Definition of "Risk" (Summit A7 session - Tues PM1)

### ISSUE THREAD

**Issue by tghosth** [OWASP/Top10#13]
Based on @vanderaj 's [summary](http://lists.owasp.org/pipermail/owasp-leaders/2017-June/018415.html):

> "The basis for the OWASP Top 10 is 'risks'. I (@vanderaj) have suggested we adopt the ISO 31000:2015 standard definition for risk."

[The short definition from ISO 31000](https://www.iso.org/files/live/sites/isoorg/files/archive/pdf/en/iso_31000_for_smes.pdf):

>  "Risk is defined as the 'effect of uncertainty on objectives'"

My personal opinion is that is very broad and I slightly prefer a more condensed version that someone put forward in the first session (sorry I'm not sure who) which was:

> "Risk is defined as 'things we want to avoid'"

Whilst less pure, I think that version is easier to articulate .

**Comment by vanderaj** [comment]
This is agreed, and this issue is being closed as per community feedback, data call and survey responses.
