### ISSUE TITLE
Glossary review and QA

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#130]
I propose we push the Glossary to post RC2. If you want to review it now, that's fine too. 

QA (we must hear from a majority of project leads saying approved before closing)

- [x] Ready for review?
- [ ] Spelling
- [ ] Content
- [ ] Issues are modern, deal with apps and API?
- [ ] Recommendations are modern, deal with apps and API?
- [ ] Example scenarios, reference real world breaches? 
- [ ] Can it be any smaller without losing information?
- [ ] Links (if any) - OWASP primary sources, stable secondary sources?

**Comment by Neil-Smithline** [comment]
Decided glossary is unneeded. Removed with 722313a7acc264c6cd46644d69d2af0913280ba6
