### ISSUE TITLE
RC2 - A2 Authentication

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#133]
https://github.com/OWASP/Top10/blob/master/2017/en/0xA2-Authentication.md

The phrase "credential stuffing" isn't widely used.  You might want to add a small * to it and a link to the OWASP article at the bottom (there is a link later on but you don't want the reader to get to the bottom of the section without knowing what it means).  Here's the link: https://www.owasp.org/index.php/Credential_stuffing

"users who you might have a legal relationship" -> "normal users"

Since you mentioned NIST, NIST says that PBKDF2 is also approved (I think as well as others), not just Argon2 (not sure how many libraries are currently available for Argon2)

"Implement weak password checks, such as testing a new password against a list of the top 10000 worst passwords"

NIST does recommend getting rid of complexity rules, but at least we should encourage longer passwords (NIST recommends a minimum of 8 up to 64) in cases where MFA can't be implemented.

"when credential stuffing, brute force or other attacks" -> "when credential stuffing, brute force or other attacks occur"

Add a link to worst password lists: https://github.com/danielmiessler/SecLists/tree/master/Passwords

"Implement rate limiting to limit the impact of automated attacks, credential stuffing, brute force, and default password attacks".  I think this is impractical to ask people to use this for all applications.  In fact, if my memory serves me correctly, I think this was reserved for Level 2 or even Level 3 applications in ASVS.  Asking users to add this is impractical (perhaps just have it as a recommendation at the end of this section)

Perhaps add an increased password length with no complexity rules as a fall back mechanism if MFA is not an option or is too difficult to implement

No mention of protecting the different authentication channels (password reset, etc.) and enumerating valid users

**Comment by ossie-git** [comment]
To add to my previous comments, just a heads up:

you point to the OWASP Authentication Cheat Sheet which recommends password complexity (https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Password_Complexity) while the main body of the text is based off NIST 800-63 which recommends abandoning complexity

Perhaps the link should be replaced with a link to the password section of NIST 800-63 - https://pages.nist.gov/800-63-3/sp800-63b.html#appA

**Comment by vanderaj** [comment]
We will have to address this issue post RC2 as we're really close to freezing RC2 text. 

@jmanico - please see comments on Authentication Cheat Sheet which I 100% totally agree with. I hate password complexity with a hatred that burns as hot as the sun.

**Comment by ossie-git** [comment]
@vanderaj If you do get rid of the complexity requirements in the Authentication Cheat Sheet, I think that adding mitigating controls would be recommended.  For example, if you aren't using MFA, then add 1 character to the minimum password length required.  If you aren't doing rate limiting, then add another character to the minimum password length required.  I think this should also be added here.

Also, NIST has some additional recommendations not covered which can be covered if you update the Authentication Cheat Sheet (such as blocking the name of the service from being used + it would probably be a good idea to block the user's name from being part of the password)

**Comment by vanderaj** [comment]
Please review the changes. We have limited space, so I've done the best I can. There might be some snips to make it fit
