### ISSUE TITLE
RC2 - A3 Sensitive Data Exposure

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#134]
HIIPA -> HIPAA

"data in rest" -> "data at rest"

"such as using TLS" -> "by using TLS"

"This is a requirement that modern browsers will start enforcing by the time the OWASP Top 10 2017 is released." -> This is a little ambiguous.  HTTPS is what will be required, not HSTS.

"They are currently alerting to unencrypted sites, and most now prevent login form submissions over clear text" -> Unless I'm mistaken, the second part of this is incorrect and you can login over clear text, you'll just the alert

In the "Example Scenarios" section, it's not clear how "public key encryption" would help prevent credit card # theft is the application requires access to it.  I think dropping the "public key encryption" part would make the recommended solutions more straight-forward

I'd add a link to the OWASP Secure Headers Project - https://www.owasp.org/index.php/OWASP_Secure_Headers_Project

**Comment by jmanico** [comment]
+1 astute notes

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by vanderaj** [comment]
Amazing comments. All included. Thank you!

**Comment by ossie-git** [comment]
Had a look at it.  Looks good.  Thanks.
