### ISSUE TITLE
R2 - Introduction

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#137]
This is kind of subjective, but in the current state that it is in, I would suggest we remove mention of the OWASP Code Review Guide.  The project needs a ton of work.  I've reviewed 3 OWASP projects so far (Top 10, Proactive Top 10 and ASVS) and sent feedback for all of them and started reviewing the OWASP Code Review Guide and was overwhelmed by how much work was needed to get the document in good form.  I went through about 30 pages of the document and sent the author a lot of feedback but probably won't spend time reviewing the rest of it due to the immense work / rewriting needed.

I'm not sure if any of you have had a recent look, but the project still needs a lot of work so it might not be a good idea to recommend it at the current time.  I can recommend any of the other 3 projects I've had a look at but wouldn't currently recommend the Code Review Guide.

I'm sure the author(s) put in a lot of effort but it still needs to move along quite a bit before it can be easily used.

**Comment by jmanico** [comment]
+1 I agree with this comment 100% and stopped suggesting folks read it a while ago. No offense to anyone at all intended, it just needs work before it’s ready for consumption.

Aloha, Jim

**Comment by Neil-Smithline** [comment]
Thanks for the input. We've been looking to remove stale references. We'll look at this one.

**Comment by vanderaj** [comment]
Yep, consider this gone before RC2.

**Comment by sslHello** [comment]
Some more suggestions:
- Replace the 'TBA's
- Add links for OWASP Testing Guide, OWASP Code Review
- Add Application Managers -> "What's Next For Developers, Verifiers, Organisations and Application Managers"

**Comment by vanderaj** [comment]
This has now been addressed in the PPTX
