### ISSUE TITLE
R2 - A6 Access Control

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#138]
abscense -> absence

"SAST and DAST tools can detect the abscense of access control, but not verify if it is functional" -> I think: "SAST and DAST tools can detect the absence of access control but can not verify if access control is functional when it is present"

anonymous attackers -> attackers

malicous -> malicious 

initating -> initiating 

adminsitrators -> administrators 

"Monitoring and escalate access control" -> "Monitoring and escalating access control" 

I think that adding a statement or two about about ensuring that access controls tokens (cookies, JWTs, etc.) can and are revoked by the application when needed (including during logout and privilege changes).  This is more so as developers typically use JWTs without expiry dates (or with very long expiry dates) and with no way to easily invalidate them.

Perhaps add a line about mass assignment attacks

**Comment by vanderaj** [comment]
Let me have a crack at this prior to RC2 freeze, but don't be surprised if some of this gets pushed.

**Comment by sslHello** [comment]
Hi ossie-git.
Thank you very much for your comments. I've just done the remaining ones.
For Session IDs we are compiling an advice in A2 (How to Prevent). I hope this fits also to your last comment.
Cheers Torsten

**Comment by vanderaj** [comment]
I've QA'd this item, and I think it's now closed.

**Comment by vanderaj** [comment]
[OWASP Top 10 2017 GM (en) master A5.pdf](https://github.com/OWASP/Top10/files/1465589/OWASP.Top.10.2017.GM.en.master.A5.pdf)
