### ISSUE TITLE
R2 - What's Next for Security Testing

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#146]
Missing links for the following:

OWASP Benchmark Project

**Comment by jmanico** [comment]
Please do not add the OWASP Benchmark. It’s a very controversial project that is made to support one vendor. It’s a significant disservice to highlight it in the OWASP Top Ten.

Aloha, Jim

**Comment by ossie-git** [comment]
@jmanico I didn't add it.  It is already mentioned in this section.  I was just commenting that there was no hyperlink to it.  But I agree, it would probably be better to remove it

**Comment by vanderaj** [comment]
If anything we need to probably remove Benchmark if it's not currently maintained. T10 has to survive intact until 2020.

**Comment by vanderaj** [comment]
If at some future state that Benchmark picks up again, and gets more coverage of the ASVS or OWASP Top 10, happy to think about re-inclusion for 2020.
