### ISSUE TITLE
R2 - What's Next for Developers

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#147]
Missing links for the following:

OWASP Secure Software Contract Annex
OWASP Prevention Cheat Sheets
OWASP Developer's Guide
OWASP Software Assurance Maturity Model (SAMM)

**Comment by vanderaj** [comment]
I decided to delete the Developer Guide. It's gone down to a Lab project, so until it's re-released and regains Flagship status, I would hesitate to include it as a lot of the content is a bit stale or else in a huge state of flux.
