### ISSUE TITLE
R2 - What's next for Application Managers

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#148]
I'd replace "security concept" by some other term

"Rate the fulfillment of all technical requirements including a rough planning and design" -> "a rough planning and design"??  Perhaps you meant a rough planning and design phase

"Consider to use templates and checklists" -> "Consider using templates and checklists"

In the "Planning and Design" section, add a sentence at the beginning:

For planning and design, you want to:

"according the protection needs" -> "according to the protection needs"

In the "Deployment, Testing and Rollout" section,

"It's critical that security tasks" -> "It's critical that the following security tasks are performed:"

"Automated the secure setup of the application ..." -> "Automate the secure setup of ..."

"integration to the IT architecture, coordinate business tests" -> "integration with the IT architecture as well as coordinate business tests"

"Consider to test use and abuse " -> "Consider testing use and abuse "

"where the application is going to be"??? -> just drop this and have "and the level of security required by the application"

"migrate form previously used applications" -> "migrate from previously used applications if needed"

In the "Operating and Changes", I would add a sentence at the beginnign:

To ensure secure operations and changes, the following should be performed:

"Regularly report all users and authorizations to the application owner and get them acknowledged" -> this makes no sense in publicly accessible sites or even internal sites with thousands of users.

In the "Retiring systems", I would add the following sentence:

The process of retiring systems is often overlooked.  You should ensure that:

"Regard any requirements for archiving data" -> Any required data is archived.  All other data is securely wiped

**Comment by vanderaj** [comment]
We will have to address this issue post RC2 as we're really close to freezing RC2 text.

**Comment by vanderaj** [comment]
Done. We're probably going to have to chop some of this out, because it's too much text for the space we have. Have a look at this, and see if there's something more we can do better.
