### ISSUE TITLE
Add some 'Risk - Application Security Risks' content and resort the risks pages

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#156]
The suggested order of the RISK pages:
1. Risk - Application Security Risks
2. R - Note about the risks
3. F - Details about Risk factors

propabely 'Risk' and 'R' could be merged that they will be 2 pages at the end

- Replace TBA
- add that this is a simplified risk rating
- Add 'CWE-' to 514/740 etc
- Consider to move 'Additional Risks to consider' to the last page (actually named 'References')
- add the formula, even if it's decribed and shown in th image, e.g. 
   1/3*(explotability + prevalence + detectibility) * technical_impact
- besides the business impact also the thread agent in not included, as we have not duistingished between internal applications, B2B apps and internet apps

**Comment by vanderaj** [comment]
Ordering seems to have been done
CWE done
Not sure about the simplified risk rating
References is gone, and so is additional risks to consider
Seems like the formula has been taken care of, let's talk about it during post RC2 to discuss diagrams and look and feel more generally. 
I don't think we're gonna be able to do that
