### ISSUE TITLE
Improve to keep apart content from 'Am I vulnerable' from 'How to Prevent' and 'Example Scenarios' 

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#157]
Suggested QAs:
+ to solely describe issues that make the application vulnerable in the 'Am I vulnerable section' (no preventions, even missing ones, sometimes this may be only a question of wording)
+ In 'how to prevent' please only positive actions to check (no scenarios)
+ Example Scenarios should only desribe misuse scenarios (no prevention, or no weakness)

=> Content should be rephrased according to the **perspective of the paragraph** or moved, e.g. missing controls from 'vulnerable' to controls in 'prevention'.

Cheers Torsten

**Comment by vanderaj** [comment]
Can this be closed?

**Comment by sslHello** [comment]
Found last issues -> opened  #346 and #339
