### ISSUE TITLE
A8: Deserialization

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#161]
Some proposals to add:
- Security weakness: Through deserialization arbitrary classes of all installed ones could be adressed, also vulnderable classes. 

Am I vulnerable: 
- Are there any objects that are sent via the browser and contain serialized data, e.g. tokens, hidden values

How to prevent:
- change to a REST or SOAP communication without using serialization

**Comment by vanderaj** [comment]
1. No room, sorry
2. Accepted
3. Accepted

Also sync'd A8 in Github

I've fixed the missing scenarios.
