### ISSUE TITLE
A10 Insufficient Logging & Monitoring

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#162]
Headline should be : 'A10 Insufficient Logging & Monitoring'

Some suggestions:

How do I prevent:
- Generate valuable error messages directly where they occure and add original messages received from libraries
- store all logs for a sufficient time to be still available for forensic analysis
- log also information from your infrastructure components, e.g. firewalls 

3rd scenario:
An attacker uses the same password and scans for any user using it. So he could take over all accounts using this password. For all other users this scan leaves only 1 false login behind. After some days this may be repeated with a different password.  

Cheers Torsten

**Comment by vanderaj** [comment]
I've added the item for forensic logging. We do not have room for the other points.
