### ISSUE TITLE
PPT: Need to adjust fonts, and spacing between paragraphs and on bullets

### ISSUE THREAD

**Issue by Neil-Smithline** [OWASP/Top10#164]
We need consistency!

- Sections must line up between pages
- Spacing between paragraphs
- Spacing after bullets
- Purple boxes must be same color and size
- Fix spacing and invisible chars in ToC

**Comment by vanderaj** [comment]
I'll do the fonts and color change, but will leave the rest to Torsten

**Comment by sslHello** [comment]
I've done a lot of them yesterday in the PPTX. 
Sometimes they reappear if new content in included.
This task will stay open until Milestone Golden Master is reached, probably until the very final version

**Comment by vanderaj** [comment]
Can this be closed?

**Comment by sslHello** [comment]
Last QA will be done within #247
