### ISSUE TITLE
A6 - Replace "browser" with "client"

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#17]
In A6, I think you should replace browser with the client as the client may be other applications, not just browsers (unless this is intentional because you are isolating API-related issues to A10)

**Comment by vanderaj** [comment]
Osama Elnaggar

**Comment by jmanico** [comment]
The formal term here is UA - User Agent. Even dev's get that.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by sslHello** [comment]
Issue resolved by the update above. Please review updated texts.
Cheers Torsten

**Comment by sslHello** [comment]
Correction: Commit 60e7dfd is related to issue #77 not #17
