### ISSUE TITLE
Convert Markdown to owasp.org

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#170]
Relies on #169 being complete. Probably makes sense to do *after* GM. 

@Neil-Smithline @sslHello who wants to do this?

**Comment by sslHello** [comment]
I'l try to compile a script that helps us to do less manually copy & pase

**Comment by katyanton** [comment]
Hi - just following on this issue, do you have an update when the wiki version for OT10 2017 will be available ?

**Comment by sslHello** [comment]
Hi Katy,

I am happy to let you know that we've compiled the Top 10-Wiki completely.
I am sorry, it took some more time as we expected before, especially during the holiday times.
You are kindly invited to review the [wiki pages](https://www.owasp.org/index.php/Category:OWASP_Top_Ten_2017_Project) for any issues.

The yellow temporary header is going to disappear when we will link it officially from the project page in some days.

Thank you and cheers
Torsten

**Comment by sslHello** [comment]
Hi - I've received no issues about the [wiki pages](https://www.owasp.org/index.php/Category:OWASP_Top_Ten_2017_Project) -> They are officialy linked at the [Top 10 Project page](https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project).
=> Closing issue #170
