### ISSUE TITLE
XSS is not the second prevalent issue now

### ISSUE THREAD

**Issue by SPoint42** [OWASP/Top10#173]
is the 7th.

**Comment by SPoint42** [comment]
See my commit

**Comment by vanderaj** [comment]
@infosecdad - Data issue for you. Please review.

**Comment by infosecdad** [comment]
@SPoint42 Apologies, I can't determine what you are referring to.  Could you please elaborate?

**Comment by infosecdad** [comment]
No response, closing issue. If follow up is needed, please let me know.
