### ISSUE TITLE
Replace "Am I vulnerable to" with anything better...

### ISSUE THREAD

**Issue by starbuck3000** [OWASP/Top10#179]
The majority of the audience reading the Top 10 document from start to end is probably not the actual owner of the system nor the application itself... Consequently, the vast amount of references such as "Am I vulnerable to...", "What is MY risk...", etc. do not apply to the reader. This was already raised in 2010 and 2013, maybe this time we could improve this?

Proposition is to replace phrases starting with:
- "Am I vulnerable to...?" 
- "What is MY risk?"
- etc.

with alternate phrasings such as:
- Is the/my application vulnerable to...?
- Is the/my system vulnerable to...?
- What is the risk? / What are the risks?

**Comment by sslHello** [comment]
Hi @starbuck3000,
thank you for your suggestions. We will definitely discuss this for the 'Golden Master'.
Cheers Torsten

**Comment by vanderaj** [comment]
Hi Torsten, I'll have a chat with everyone at next Friday's meeting and let's think about how we can make it better. I'll allocate you and me to resolve once we've made a call on it.

**Comment by jmanico** [comment]
+1 this should be easy to apply and is a very reasonable clarification. And it just reads better...

**Comment by Neil-Smithline** [comment]
The same person should fix this and #236 - thanks for catching this @sslHello.

I am thinking that the heading should be `Is My Application Vulnerable to This?` I've confirmed that this fits in the PPTX.

**Comment by Neil-Smithline** [comment]
Text from @drwetter from #236:
> Am I Vulnerable to Broken Auth?, Am I Vulnerable to Broken Access Ctl?, Am I Vulnerable to Security Misconfig? IMO shouldn't be a headline in a box.

> I assume this is mostly for space reasons but I would recommend to just use the headline Am I Vulnerable to This?. It would be also consistent with the box on the right hand side.

**Comment by Neil-Smithline** [comment]
I am thinking that the heading should be `Is My Application Vulnerable to This?` I've confirmed that this fits in the PPTX.

**Comment by starbuck3000** [comment]
Why not something like:
"Is the application vulnerable?"
or
"Is the system vulnerable?"

It's short, clean, unambiguous and grammatically correct.

**Comment by vanderaj** [comment]
Is the application vulnerable?
How to prevent?

**Comment by Neil-Smithline** [comment]
We are going to change it to `Is the System Vulnerable?`. We are also going to change the prevention box to `How Do I Prevent?`.

Thanks everyone for the feedback!

**Comment by drwetter** [comment]
Sounds snappy! 

Not sure about "the System" though but English is not my mother tongue. By "the System" I would understand a web / app or DB server and not the whole thing as you probably meant?

**Comment by Neil-Smithline** [comment]
Darn - I meant to say `Is the Application Vulnerable?` as that is the text we use everywhere else.

**Comment by sslHello** [comment]
Hi Neil, 
I've canged the text in A1 - A10 to
- Is the Application Vulnerable?
- How To Prevent? 
Please feel free to change if you liked.
Cheers Torsten

Commits: 58e6219, dc320f2, 369813d, f77f36a, 9fc45ea, c6ef58d, 1c4e2f0, df696cb, 499312e, f354619

**Comment by sslHello** [comment]
'How To Prevent?' -> 'How To Prevent'

**Comment by sslHello** [comment]
fixed
