### ISSUE TITLE
drop ESAPI from all of Top 10

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#18]
Osama Elnaggar

pg. 8 - A1 Injection
I think dropping the mention of OWASP ESAPI would be better as even its authors are no longer recommending its use (https://www.owasp.org/index.php/Category:OWASP_Enterprise_Security_API#tab=Should_I_use_ESAPI_3F) in addition to the following: "Given that I'm the ESAPI project co-lead, you might think I'd be more inclined to recommend ESAPI, but I don't except in rare cases" - http://lists.owasp.org/pipermail/esapi-dev/2017-February/002656.html 
I think that mention of ESAPI should be removed across the standard.

**Comment by vanderaj** [comment]
pg. 18 What's Next for Developers
I would remove the mention of a reference model of ESAPI as mentioned previously

**Comment by jmanico** [comment]
👍🏼👍🏼

I have a decent list of encoder libraries across many languages if interested -owasp and others alike.

Aloha,
--
Jim Manico
@Manicode

**Comment by Neil-Smithline** [comment]
@jmanico - Does it make sense to put that page somewhere on the OWASP wiki? That would allow us to reference the wiki page in the T10.

**Comment by jmanico** [comment]
I suggest linking to https://www.owasp.org/index.php/Injection_Cheat_Sheet and we'll add more references there. Cool?

- Jim

**Comment by Neil-Smithline** [comment]
@jmanico - The Injection Cheat Sheet is currently empty, just a place holder. I can't reference that in the T10. For now I'm just going to delete the references. If you know of a better reference or one of us has time to update the Injection Cheat Sheet, we can change the reference then.

**Comment by Neil-Smithline** [comment]
ESAPI references removed

**Comment by jmanico** [comment]
Ah, I’ll make sure it’s in draft mode so we work on it.  Makes sense to drop it for now...

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805
