### ISSUE TITLE
Scenario #x - Normalize look and feel

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#181]
Make "Scenario #x:" bold
Remove underlining (it makes it hard to read @ 9 pt on printed version)

**Comment by vanderaj** [comment]
Aligned in both PPTX and Markdown. Went with bold and no underline to make the scenarios stand out, especially on risks where there's a lot of scenario text, and less examples

**Comment by sslHello** [comment]
A7 and A10 are still affected by this

**Comment by sslHello** [comment]
Fixed
