### ISSUE TITLE
A6: Security Misconfiguration has too many scenarios

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#182]
5 is too many. Choose 3 and make them better.

**Comment by sslHello** [comment]
Depends on the decision of #252

**Comment by sslHello** [comment]
Merged 1 and 4, extended Scenario 3.
=> 4 Scenarios -> Discussion

**Comment by sslHello** [comment]
Fixed, ready for QA

**Comment by vanderaj** [comment]
QA'd
