### ISSUE TITLE
A2 Mention use of framework in "How Do I Prevent This" section

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#19]
Osama Elnaggar

pg. 9 - A2 Broken Authentication & Session Management
In the "How Do I Prevent This?", I would probably add the recommendation to use well known and tested frameworks that tackle these issues (Apache Shiro, Spring Security, etc.) instead of recommending providing an interface similar to ESAPI Authenticator and User APIs.  Almost all frameworks come with mature authentication and authorization frameworks that can be leveraged.  Trying to roll out your own as most development teams would probably develop in-consistent and in-secure interfaces

**Comment by jmanico** [comment]
The trend I see it not to use shiro or spring sec - both have massive insecure default settings.

The trend is commercial identity products like Okta or Ping. I would not wish Shiro or SpringSec on my worst enemy....

--
Jim Manico
@Manicode

**Comment by vanderaj** [comment]
Resolved in latest update. Please review.
