### ISSUE TITLE
Reference section

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#193]
We still have a good reference page in markdown

- Extract all URLs from the document
- Create a list of them in a major reference page
- Review all of them to make sure they are https
- Review all of them to make sure they are up to date and say what is necessary in 2017
- Fix (if at owasp) or Replace any references that are not good in 2017

**Comment by sslHello** [comment]
We should update all Testing Guide links from V3 to V4 
[OWASP Testing Project](https://www.owasp.org/index.php/OWASP_Testing_Project)

**Comment by sslHello** [comment]
Probably old V3 hints have not been deleted in the wiki by the OWASP Testing Project

**Comment by vanderaj** [comment]
To be removed

**Comment by vanderaj** [comment]
Removed
