### ISSUE TITLE
+O enhancement BSIMM8 for measuring org

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#197]
We should also mention BSIMM 8 for measuring an organization's maturity as well as SAMM. Measuring is BSIMM's thing, it's open and they have many orgs contributing to it.

**Comment by vanderaj** [comment]
Not going link BSIMM, Links to individual SAMM pages to be removed / changed.

**Comment by infosecdad** [comment]
I added a direct mention of SAMM, we are going to keep the references for now. If SAMM undergoes changes before this document is refreshed, we will maintain forwarding for the affected links.
