### ISSUE TITLE
Normalize "NB" throughout the document

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#199]
Most of the time we use NB in bold. Let's make that the default everywhere.

**Comment by sslHello** [comment]
fixed.

@vanderaj Andrew should we also standardize the NB text for the 'OWASP Secure Software Contract Annex'?
+D: "NB: The annex is for US contract law, so please consult qualified legal advice before using the sample annex."
+A: "NB: Please note that the Annex is a sample specific to US contract law, and is likely to need legal review in your jurisdiction. Please consult qualified legal advice before using the Annex."
Cheers Torsten

**Comment by vanderaj** [comment]
This seems to have been fixed in the current draft by replacing NB with Note:

I've made sure all examples are bolded.

**Comment by vanderaj** [comment]
This has been resolved in the markdown version by someone as well.
