### ISSUE TITLE
+R "Although the 2007" -> "Although the OWASP Top 10 2007"

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#202]
This sentence isn't quite right. Suggest changing it to 

"Although the OWASP Top 10 2007"...

**Comment by sslHello** [comment]
I'd suggest to discuss if we update the whole patragraph.

**Comment by vanderaj** [comment]
The OWASP Top 10's focus on risks has caused some confusion on the part of people searching for an airtight weakness taxonomy.

**Comment by vanderaj** [comment]
Numbers missing

**Comment by infosecdad** [comment]
Updated the +R page to address.
