### ISSUE TITLE
pg. 12 - A6 Sensitive Data Exposure

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#21]
Osama Elnaggar

pg. 12 - A6 Sensitive Data Exposure
In the "How Do I Prevent This?", I would add not to use the default crypto keys used by some frameworks and to generate your own.  Many frameworks allow a single secret key to generate "recover my account" URLs, encrypt data stored on the client side, etc.  These aren’t “weak” keys, but they are known keys that can be abused by an attacker

**Comment by jmanico** [comment]
I would push devs in the direction of tokenization designs, vaultproject.io, HSM's or other key vaults or crypto services. When app devs even touch keys problems ensue.

--
Jim Manico
@Manicode

**Comment by sslHello** [comment]
Hi Osama,

many thanks for your nice suggestion.
I've added it to 'Am I vulnerable to attack? Example no4:'
'Are default crypto keys in use, weak crypto keys generated, or is proper key management or rotation missing?'
I hope this solves your findings. Issue resolved. Please review updated text.
