### ISSUE TITLE
Should A7 Cross Site Scripting be changed to Client Side Attacks?

### ISSUE THREAD

**Issue by kerberosmansour** [OWASP/Top10#210]
Based on #174 discussions with @jmanico, is it worth changing A7 to encompass client side attacks so it could cover over XSS, Open Redirect, CSRF and Improper client side storage of sensitive data....

As Stated its a bit late in the process, but for Open Redirect alone there is data to support this:

**Fortify:**
Number of Unchecked Redirect Vulnerabilities Found (CWE-601) - 29494
Number of XML eXternal Entity Injection (XXE) Vulnerabilities Found (CWE-611) - 27864
Result: **1630** more incidents involving Unvalidated Redirect than XXE

**Veracode:**
URL Redirection to Untrusted Site (Unvalidated Redirect) (CWE-601) - 56029
Improper Restriction of XML External Entity Reference (XXE) (CWE-611) - 41673
Result: **14356** more incidents involving Unvalidated Redirect than XXE

**Synopsys:**
CWE-601 (Unvalidated Redirect) = 36 incidents
CWE-611 (XXE) =3 incidents
Result = **33** more incidents involving Unvalidated Redirect.

**Comment by Neil-Smithline** [comment]
In principle I like this idea, but, and it's a big but, I question how much we can put into one issue. There's just so much room.

**Comment by jmanico** [comment]
This is just an idea that I’m not tied to. XSS is not only a client side risk; same with CSRF....

**Comment by kerberosmansour** [comment]
@Neil-Smithline & @jmanico all I could do is provide my feedback, state the case for this issue, and hope it helps.

There are several vulnerabilities with high incident rate per CWE like the Open Redirect & CSRF that in the OWASP Top Ten's current form. This is from the Data Analysis own data:
![image](https://user-images.githubusercontent.com/13433538/31865423-cdbc5546-b766-11e7-96df-5408007f39d5.png)

I would strongly reconsider given the impact these types of vulnerabilities have, e.g:
consider the two attacks below:

During US election Open Redirects were used to in GMail as part of a disinformation campaign https://motherboard.vice.com/en_us/article/mbqzq8/russian-hackers-are-using-googles-own-infrastructure-to-hack-gmail-users

The UK Tax Authority HMRC (their equivalent of the IRS) also had an issue with redirects: http://www.bbc.co.uk/news/technology-41188008

**Comment by davewichers** [comment]
No! Absolutely not. (In my opinion :-) ). XSS is an attack that happens in
the browser, but the vulnerable code causing the problem can be in server
side code ONLY, client side code ONLY, or a combination of both. And there
is also both stored and reflected types of these 3 XSS issues. As such, I
think sticking with the name of the vulnerability (XSS) is best, and then
trying to explain these 3 types of XSS would be helpful, but is hard
because there is not enough room in the T10 to do the topic justice

I tried here and hopefully the T10 does, or will, link to this article:
https://www.owasp.org/index.php/Types_of_Cross-Site_Scripting and retains
the use of the terms client and server XSS that I believe were in the RC1
2017 draft.

-Dave

**Comment by davewichers** [comment]
Guess I should read the original post in detail not just the title before responding. Oops. I see the suggestors point, but don't think we should change XSS to this broader category.

Dave

**Comment by kerberosmansour** [comment]
@davewichers no worries, and I am grateful for your feedback David. What are your thoughts on the other missing issues though. I am concerned with **Open Redirect** especially going away given the data, and its impact. 

My feedback that if it doesn't deserve a top ten on its own given all the other issues, should we consider where else can it be included?

Thoughts anyone?

**Comment by kerberosmansour** [comment]
@DinisCruz @securestep9 thoughts?
Did you see this discussion with Alex Stamos? https://twitter.com/alexstamos/status/923348404045881344

**Comment by infosecdad** [comment]
We have updated the Additional Risks to Consider to include Open Redirect and other important, but not in the Top 10, categories.

**Comment by kerberosmansour** [comment]
Thanks @infosecdad
