### ISSUE TITLE
Website landing page needs updating

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#214]
The landing page at https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project is outdated. 

[ ] Close off all activities that are closed off, like the data call and survey
[ ] Make the RC2 announcement more in line with something that we're likely to use elsewhere

**Comment by infosecdad** [comment]
Updated the landing page, we'll need to update again when the GM is released.

**Comment by vanderaj** [comment]
This has been taken care of, closing
