### ISSUE TITLE
Primary sources

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#217]
I've found at least one link to Wikipedia. I'd like to only have primary sources (i.e. OWASP or someone authoritative on the topic). 

- DTD link to Wikipedia. Replace with W3c or OASIS or similar. 

Blog entries are okay, but as external references after the primary reference.

**Comment by vanderaj** [comment]
A3, A4, A9

**Comment by infosecdad** [comment]
I replaced all wikipedia references save two, I could not find a decent replacement reference for bcrypt and PBKDF2
