### ISSUE TITLE
A7: pg. 14 - Insufficient Attack Protection

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#22]
I think that this section addresses an issue that has been missing for a long time.  I would probably rename this section to Detection and Prevention and expand on logging of all sensitive function access, failed requests due to malicious input, etc. and not just rely on a WAF or RASP (although doing so is the recommended approach for virtual patching).  Prevention is ideal, but detection is a must.  Also, some issues related to attack prevention such as IDOR abuse (if the attacker rate limits themselves) won't easily be detected by WAFs, etc. because the input itself is not malicious.

**Comment by vanderaj** [comment]
Osama Elnaggar

**Comment by jmanico** [comment]
PS: The term IDOR is not a good one, in my opinion. It's not the language of developers. A better term is "data contextual access control" or similar.

Aloha,
--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
Otherwise, I like this comment a lot Andrew. In fact, I think to simplify consider a focus on detection since it informs protection.

"Security logging" and similar is something developers can act on in powerful ways without much instruction.

Aloha,
--
Jim Manico
@Manicode

**Comment by vanderaj** [comment]
This risk is going to be removed as per community feedback at the Project Summit, survey data and revised data call. Thank you for your input on this matter.
