### ISSUE TITLE
A9 - missing links

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#222]
Need links to OWASP Proactive Controls, ASVS, Testing Guide
Need links to CWE for this issue

**Comment by Neil-Smithline** [comment]
I have decided not to include a CWE link for this one. The only relevant CWE is [CWE-937: OWASP Top Ten 2013 Category A9 - Using Components with Known Vulnerabilities][https://cwe.mitre.org/data/definitions/937.html]). It contains no useful information, hence I'm not including a link to it.

**Comment by Neil-Smithline** [comment]
I also don't believe that there's a relevant [proactive control][https://www.owasp.org/index.php/OWASP_Proactive_Controls#tab=OWASP_Proactive_Controls_2016] for this issue.

**Comment by Neil-Smithline** [comment]
Lastly, there's no relevant cheatsheet.

Other than the above, I've done everything asked for.
