### ISSUE TITLE
A9 - Add synk to PPTX

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#223]
We had a merge with https://snyk.io/vuln in the Markdown version

Let's talk if we include freemium projects. They have a free tier, but ... we need to come up with an inclusion policy that is vendor neutral, and I think freemium ... is a bit iffy. Let's talk about it on Friday. I've not incorporated this change into the PowerPoint at this time, and will not until after we've talked.

**Comment by Neil-Smithline** [comment]
I'm concerned about the appearance of bias. Especially after the RC1 reaction and that we'd be slipping the reference into the final release while it wasn't in RC2. I (regrettably) vote no.

**Comment by vanderaj** [comment]
Decision by leaders (Torsten, Neil, Andrew) to remove commercial / freemium tools and services to maintain OWASP neutrality.

**Comment by vanderaj** [comment]
ELK
Synk (remove from the master branch)

**Comment by jmanico** [comment]
Thank you for this wise decision.

**Comment by Neil-Smithline** [comment]
@vanderaj - I removed the reference to ELK, but am not sure where the reference to Synk is. I looked in A9 in both the master and golden-master branches. Either it has already been removed (great), or I'm missing it. Can you let me know? If it's gone, feel free to just close this issue.

**Comment by sslHello** [comment]
I think it's done now

**Comment by Neil-Smithline** [comment]
Ah! Andrew mistyped it as "synk" and I was just searching for that instead of "snyk". Thanks for fixing it Torsten.
