### ISSUE TITLE
Typo in HIPAA in "Am I Vulnerable to Data Exposure" section

### ISSUE THREAD

**Issue by sreenathsasikumar** [OWASP/Top10#226]
In the "Am I Vulnerable to Data Exposure?" section, HIPAA has been misspelled

The sentence "such as PCI Data Security Standard (PCI DSS), or health records laws, such as Portability Act (HIIPA)" 
should be 
"such as PCI Data Security Standard (PCI DSS), or health records laws, such as Portability Act (HIPAA)"

**Comment by vanderaj** [comment]
Done
