### ISSUE TITLE
Typo in "Am I Vulnerable XSS" A7 Section

### ISSUE THREAD

**Issue by sreenathsasikumar** [OWASP/Top10#228]
The word "There" is misspelled as "Three"

In the "Am I Vulnerable XSS" section,
"Three are three forms of XSS, usually targeting users' browsers" should be 
"There are three forms of XSS, usually targeting users' browsers"

**Comment by vanderaj** [comment]
Small change, I got this.

**Comment by vanderaj** [comment]
Done
