### ISSUE TITLE
Typo in "malvertizing" in "Am I Vulnerable XSS" A7 section

### ISSUE THREAD

**Issue by sreenathsasikumar** [OWASP/Top10#229]
The word malvertising has been misspelled as malvertizing.

In the "Am I Vulnerable XSS" section, 
"Typically the user will need to interact with a link, or some other attacker controlled page, such as a watering hole attack, malvertizing, or similar." should be 
"Typically the user will need to interact with a link, or some other attacker controlled page, such as a watering hole attack, malvertising, or similar." should be

**Comment by vanderaj** [comment]
Small change, I've got this

**Comment by vanderaj** [comment]
Done
