### ISSUE TITLE
Grammar error in "Am I Vulnerable" A9 section

### ISSUE THREAD

**Issue by sreenathsasikumar** [OWASP/Top10#230]
The sentence "If you do not fix nor upgrade the underlying platform" in  "Am I Vulnerable" A9 section should either be
1. If you do not fix or upgrade the underlying platform
1. If you neither fix nor upgrade the underlying platform

**Comment by vanderaj** [comment]
Small change, I got this.

**Comment by vanderaj** [comment]
Done
