### ISSUE TITLE
Input Validation - the words "server-side" missing in Injection, XSS and other risks

### ISSUE THREAD

**Issue by securestep9** [OWASP/Top10#234]
Almost everywhere in the document the words "input validation" must have "**server-side**" in front as a clarification. WIth proliferation of JavaScript apps and mobile apps/APIs the Top 10 document should explicitly state that validation must be done on the server-side as the client-side validation can be trivially bypassed by turning off Javascript/submitting the request using OWASP ZAP,curl or any other non-browser/non-mobile-app tool.
 We have seen way too many applications where developers perform input validation only on the client-side claiming that _"nowhere in the OWASP Top-10 there is a statement that input validation must be performed on the server-side"_

The words "server-side" were missed out in OWASP Top 10 2013 - we must make sure that the same mistake doesn't happen in 2017. CC : @davewichers 

Changes shold be made in the document on pages:

Page 8 ('How Do I Prevent Injection') - amended text should say:  
Positive or "white list" **server-side** input validation,
Page 11 ('How Do I Prevent This?') - amend the text to say: 
Implement positive ("white listing") **server-side** input validation
Page 17: ('How Do I Prevent This?') - amend the text to say: 
Ensure all login, access control failures, **server-side** input validation failures can be logged

**Comment by jmanico** [comment]
+1 very astute comment

**Comment by sslHello** [comment]
Thank you very much for the nice and concise suggestion. If we do have place I'd be happy to get it in the text.
It is a good prevention against a possible misunderstanding of the recommendations.
Cheers Torsten

**Comment by vanderaj** [comment]
Torsten, have a shot and make sure you update both the wiki and PPTX. I want to make sure it fits!  :)

**Comment by sslHello** [comment]
Fixed, 
@securestep9 - Sam, I have found a sufficient place to add it. Thanks
Please review the changes in Markdown, PPTX and PDF will be uploaded later.
