### ISSUE TITLE
p5: Correct A2 to be consistent

### ISSUE THREAD

**Issue by drwetter** [OWASP/Top10#235]
Hi @vanderaj ,

page 5 still lists in the table  ``A2:2017 – Broken Authentication and Session Management``. Also if I am concerned retiring session management from the Top 10, I would recommend to be consistent with the headline of A2 in the rest of the document.

Cheers, Dirk

**Comment by vanderaj** [comment]
This is already fixed in the Golden Master with commit 2796ff4f488c5c2c89619e945aa441114edf4b20
