### ISSUE TITLE
Am I Vulnerable to ...

### ISSUE THREAD

**Issue by drwetter** [OWASP/Top10#236]
``Am I Vulnerable to Broken Auth?``, ``Am I Vulnerable to Broken Access Ctl?``, ``Am I Vulnerable to Security Misconfig?`` IMO shouldn't be a headline in a box.

I assume this is mostly for space reasons but I would recommend to just use the headline ``Am I Vulnerable to This?``. It would be also consistent with the box on the right hand side.

**Comment by Neil-Smithline** [comment]
It is done for space, and I agree that it is messy.

**Comment by sslHello** [comment]
Linking to #179

**Comment by Neil-Smithline** [comment]
@drwetter - We're going to be discussing this in #179 as they're very related. Thanks for the feedback!

Closing as a duplicate of #179.
