### ISSUE TITLE
Logging is V8 in current ASVS

### ISSUE THREAD

**Issue by drwetter** [OWASP/Top10#237]
.. not V7 see reference on A10.

**Comment by vanderaj** [comment]
Thanks Dirk. At the ASVS, we are moving to Markdown as well, so we can create a Wiki version we can deep link to. I will resolve this in the text, but hopefully, by the time the OWASP Top 10 2017 releases, we can at least have locations on the OWASP Wiki for our updated content.

**Comment by vanderaj** [comment]
This is now in the text, but as I said, the link will change hopefully before the Golden Master drops.
