### ISSUE TITLE
A8 Replace Friday 13th Deck reference with new link

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#238]
Replace it with this : https://speakerdeck.com/pwntester/friday-the-13th-json-attacks

**Comment by vanderaj** [comment]
Tag @pwntester

**Comment by pwntester** [comment]
Addressed in PR #239

**Comment by vanderaj** [comment]
Merged, plus commit https://github.com/OWASP/Top10/commit/107eb6e4b87456cd474616d8cf555337b7ed93a0
