### ISSUE TITLE
A0, A7 - Feedback on Jeremiah Grossman's tweet

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#24]
Jeremiah's tweet regarding A0 (https://twitter.com/jeremiahg/status/851562562634137600) isn't actionable by developers and is more in the domain of operations or governance whereas A7 is.  A7 just needs to be re-worded and I think split up into:
* as a developer, how are you going to detect attacks?
* as a developer, how are you going to protect against detected attacks?
* as a developer, how are you going to enable quick patching when either your application is vulnerable or the 3rd party libraries you use are?
For the first, a developer could take the initiative to log all sensitive actions in the application + things that violate the security policy defined when they tackled the other OWASP Top 10 areas.  They can then decide to output this in JSON so they can be easily consumed by logging solutions within the environment and to feed their SOC teams with the necessarily visibility.
Tackling protection is more difficult for a developer but there are libraries that developers can use to help protect against brute forcing.  These won't protect against all attacks but can at least protect against things such as password brute-force attacks quite easily.  At the very least, the developer can ensure that these will be detected and that they are providing their security operations teams with the necessary logs to detect these attacks.
The last one is probably the most difficult for a developer to tackle as this is border-line outside the scope of the developer.  But then again, the "Security Misconfiguration" and "Using Components with Known Vulnerabilities" are also borderline outside the scope of the developer.  A developer may launch their application with components that are up-to-date and don't have know vulnerabilities but this isn't going to last for long.  Slide 13 from Jeremiah's talk about Cyber Insurance (https://www.blackhat.com/docs/us-16/materials/us-16-Grossman-An-Insiders-Guide-To-Cyber-Insurance-And-Security-Guarantees.pdf) covers the average time to fix in days for Known web vulnerabilities found with the average around 130 days.  So this last point is basically saying: bugs will be found on your site.  How quickly will you patch them (either permanently in the code if the vulnerability is in your code and not a 3rd party component or virtually using a WAF, RASP, etc. until it can be fixed and a new deployment rolled out)?  Having this issue on the table and addressed by developers, project managers, operations, etc is great.  Security vulnerabilities can be given greater weight and teams can try to streamline the process for developing, testing, and rolling out patches.  WAFs and RASP can add an additional layer of security until these issues are patched in the code.  Not having something like this is the reason that we see 100+ days of exposures for known web applications as highlighted in the presentation above.

**Comment by vanderaj** [comment]
From Osama Elnaggar

**Comment by jmanico** [comment]
This is just full of fantastic, thank you Andrew!

--
Jim Manico
@Manicode

**Comment by vanderaj** [comment]
This risk is going to be removed as per community feedback at the Project Summit, survey data and revised data call. Thank you for your input on this matter.
