### ISSUE TITLE
+A What’s Next for Application Managers - Abuse of functionality

### ISSUE THREAD

**Issue by clerkendweller** [OWASP/Top10#244]
_WASC-21 Insufficient Anti-Automation_ and _WASC-42 Abuse of Functionality_ didn't make it into the Top 10, but I think it might be remiss not to highlight these problems in a section like "+A", since it requires actions during Requirements, Planning & Design, Development and cannot just be an operations after-thought. Clearly the data capture for the T10 didn't rank these issues, despite them being everyday problems for most web applications. 

My suggestion is to extend the bullet item _"Compile the technical requirements including functional and non functional security requirements"_ by adding afterwards _", including consideration of functionality misuse"_.

The OWASP [Automated Threats to Web Applications](https://www.owasp.org/index.php/OWASP_Automated_Threats_to_Web_Applications) Project classifies and describes the issues, effects and possible countermeasures in a technology and vendor agnostic manner, and I would of course suggest linking to that, but since it spans multiple SDLC stages, I am not sure how best to propose it might be referenced in the new T10.

**Comment by sslHello** [comment]
Thank you for the comment.
I'd see functionality misuse in '+A' more as a testing requirement. 
'Create "use" and "abuse" test cases from technical and business perspectives.'
Perhaps (if we can find any space) this might be something to add as positive phrased business requirement to the first bullet.

**Comment by sslHello** [comment]
I am sorry, I'd not suggest to include 'WASC-21 Insufficient Anti-Automation' in '+A'. It is about the lifecycle process of an application.

**Comment by clerkendweller** [comment]
I agree not to mention specific vulnerabilities, or controls, but instead making some mention of _thinking about functionality misuse_ through the SDLC processes

**Comment by sslHello** [comment]
Your comment inspired me to add 'the expected business logic' as some important thing to be negotiated as an requirement.
Is this already close to your request (including use and abuse tests)?

**Comment by clerkendweller** [comment]
Yes, agreed. That is a good phrase.

**Comment by clerkendweller** [comment]
Er, maybe I wasn't meant to close this? I will leave it for someone else to do so!

**Comment by infosecdad** [comment]
No worries, looks like this is resolved.
