### ISSUE TITLE
FW Remove apostrophes in unpunctuated abbreviations

### ISSUE THREAD

**Issue by clerkendweller** [OWASP/Top10#245]
Please change _"CIO's and CISO's"_ to _"CIOs and CISOs"._

Ref 1  https://en.oxforddictionaries.com/punctuation/apostrophe

Ref 2  https://afterdeadline.blogs.nytimes.com/2010/04/13/faqs-on-style/

**Comment by vanderaj** [comment]
Found in Foreword (0x02)
