### ISSUE TITLE
Adjust fonts and color scheme

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#247]
Use Liberation Sans for the body
Use Exo 2 for headings

OWASP Top 10 2013: Green - (78, 133, 65) and the pale one is 80% transparent
OWASP Top 10 2017: Purple - (131, 39, 107) and the pale one is 80% transparent
Heading text to be 35% gray

**Comment by sslHello** [comment]
Could we try Liberation Sans for body and headings, please?

**Comment by vanderaj** [comment]
I'd like a bit of differentiation to them. We can try it without, but
there's a lot of effort to put it back in if we use Replace fonts

**Comment by sslHello** [comment]
Standard fond changed from Arial to Liberation Sans

**Comment by sslHello** [comment]
Changed Color + font for '+A' (in PPTX)

**Comment by vanderaj** [comment]
I've finished changing the colors, and also Exo. I saw you started on that, so I just finished it up. Let's discuss at next Friday's meeting. It's really simple now to change Exo -> Liberation Sans, but I do like the difference in heading fonts compared to the body. I've also turned the primary colors of the risks to be more subdued. I think these can be fine tuned some more.

**Comment by sslHello** [comment]
Found some Exo in the body -> fixed

**Comment by sslHello** [comment]
Adjusted the hight of the sub headlines (in light blue) to 0,93 cm.
(Hint: I've corrected also the length of the boxes, then I had to readjust the hight to 0,93 cm iteratively)

**Comment by sslHello** [comment]
Adjusted the color of the puple top boxes on the left and the lines of the page number boxes on the right

**Comment by sslHello** [comment]
Found some (new) text using 'Calibri' font -> changed it to Liberation Sans (in PPTX)
=> Should be redone at the very end of QA

**Comment by vanderaj** [comment]
I've done the replacement again, and can't see any more alternative fonts. Closing
