### ISSUE TITLE
A1 - Perhaps adding template injection at least as a reference

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#25]
2.	Soroush Dalili 
Hi Dave,   My comments are as follows. Hopefully you will find them useful:
A1: Perhaps adding template injection at least as a reference
Although template injections are similar to expression language injections, they are different and should be treated differently. We see them more these days because of all the new frameworks and the good job PortSwigger team did on researching them.

**Comment by Neil-Smithline** [comment]
Added template inclusion reference to `A1 - Injection` and `A3 - XSS`. I currently used references on PortSwigger's site, but would like more vendor neutral references if anyone knows of one.
