### ISSUE TITLE
A2: Really remove Session Management (or put it in some place else)

### ISSUE THREAD

**Issue by drwetter** [OWASP/Top10#252]
Also if session management seems not to be wished in the top 10 I would recommend to either remove all "session management" words in A2 as it is confusing. Either it is in or it is out. Currently it is out by 95%. This feels wrong to me.

See thread @ https://github.com/OWASP/Top10/issues/120#issuecomment-337378024

O(nly o)ccurences:

  * ``Is the Application Vulnerable?`` --> Confirmation of the user's identity, authentication, and session management 
  * ``References / OWASP``: OWASP Application Security Verification Standard V3 Session Management
    * ``References / OWASP``: OWASP Session Management Cheat Sheet
    * ``References / External``: CWE-384 Session Fixation

As mentioned I have concerns removing session management but this is not my point here. The most important thing to me though is that the T10 is straight and not vague.

**Comment by sslHello** [comment]
Hi Dirk,
I'll put this issue on the list for discussion. If it's not A2 it may fit in the already crowded A6. So we need to delete some content there if we include it to A6.
Cheers Torsten

**Comment by drwetter** [comment]
Hi Torsten,

thanks!

I know I am demanding at this moment much but to make my point, better would be a separate item. As mentioned besides "Session token in URL" there shouldn't be IMO much automated scanners will detect. Maybe relying purely on the data was the decision maker?

Given the fact the modern technologies like JWT has only client side controls skipping session management issues completely feels awkward as this is something which 2013 wasn't existing.

In any case a mercy thing like "lets do some name dropping of session management issues here" IMO confuses more than it helps.

Thanks again, Dirk

**Comment by vanderaj** [comment]
Server side

Put back RC1 text as a single bullet point

**Comment by sslHello** [comment]
Should we rename A2 to 'Broken Authentication and Session Management'.
NB: The relation of them is described nicely in the OWASP Cheat Sheet 'Session Management': "Once an authenticated session has been established, the session ID (or token) is **temporarily equivalent** to the strongest authentication method..."

**Comment by drwetter** [comment]
My 2cents: ``Broken Authentication and Session Management`` sounds good! 

The only thing I am wondering whether it is supposed to be read ``Broken Authentication and *Broken* Session Management``, then you could opt for just ``Authentication and Session Management``. The other case ``Broken Authentication and Broken Session Management`` would be clearer but I assume there isn't enough space for 2x "Broken"

**Comment by sslHello** [comment]
Thank you Neil

**Comment by sslHello** [comment]
Neil and I have just added a sentence about session management at the end of  'How to Prevent'  (c398eee), Ready for QA

**Comment by vanderaj** [comment]
I've been through this and reworded a few things. I'm satisfied we've re-included session management. Let's not rename it for now and see the reaction post golden master.
