### ISSUE TITLE
References need seperators

### ISSUE THREAD

**Issue by drwetter** [OWASP/Top10#253]
There needs to be a common style in the references:
 
A2: 

1. ``OWASP Proactive Controls - Implement Identity and Authentication Controls``
2.  ``OWASP Application Security Verification Standard V2 Authentication``
3.  ``OWASP Application Security Verification Standard V3 Session Management``
4. ``CWE-384 Session Fixation`` (and following)

``1`` has a hyphen, ``2`` to ``4`` miss hyphens or colons 

In A1+A3 the tendency seems more like hyphens for OWASP, for external: nada. If you would ask for my preference, that would be a colon.

**Comment by sslHello** [comment]
Hi Dirk,
yes that is just what I've started, when we figured out thar we'd liked to change the wording for the cheat sheets, too, see #250 
Cheers Torsten

**Comment by sslHello** [comment]
Hi Dirk,
fixed in Markdown and PPTX, will be uploaded later.
Cheers Torsten
