### ISSUE TITLE
NoSQL in A1

### ISSUE THREAD

**Issue by drwetter** [OWASP/Top10#254]
Following recommendations:

  * ``Is the Application Vulnerable?``: ``Some of the more common injections are SQL, OS command,`` --> ``Some of the more common injections are SQL, OS command, NoSQL, ``
  * Then: ``and Expression Language (EL) or OGNL injection.. `` --> ``and Expression Language (EL) / OGNL injection. `` <sup>1</sup>
  * alternatively removing OGNL: ``and Expression Language (EL) injection.``

For NoSQL: I feel it is more important and more actual concerning issue than EL.

For EL / OGLN:  It feels a little bit like buzzword bingo to me. :-) At least it's a subset of EL and if it's not explained only dropping the acronym leaves the reader with questions behind. So my recommendation is best to remove OGNL completely or replacing the ``or`` by ``/`` and explaining OGNL somewhere

<sup>1</sup>: Mind the double trailing dot here.

**Comment by infosecdad** [comment]
Addressed the comments, thank you!
