### ISSUE TITLE
+A: Boxes don't look good

### ISSUE THREAD

**Issue by Neil-Smithline** [OWASP/Top10#255]
The spacing of the boxes on +A causes the corners to look funny. 
![bad corners](https://user-images.githubusercontent.com/766467/32237951-b041771c-be3c-11e7-87c5-714540ef0b9d.png)
We will need to delete several lines of text to make the gray box small enough to look good.

**Comment by sslHello** [comment]
Neil - which corners do you mean? Left side?

**Comment by infosecdad** [comment]
I would make the purple boxes on the left, square, to balance.

**Comment by sslHello** [comment]
@infosecdad - Brian, I've just tried to do this. Perhaps we have to get it only one line shorter for a better fit.

**Comment by infosecdad** [comment]
I squared all the purple boxes on multiple pages, more in alignment with the rest of the document now.  If you are good with it, close this issue.

**Comment by Neil-Smithline** [comment]
Well I think the rounded corners looked a whole lot better, though the squared ones fix the consistency problems. If we decide to go with the square corners, do we make the right-hand side of the grey box square as well? Those are now the only rounded corner on the page.

![rounded-right-hand-corners](https://user-images.githubusercontent.com/766467/32250549-5cd0424e-be63-11e7-8d4a-f0ba065523f1.png)

**Comment by Neil-Smithline** [comment]
Another possibility is to make all of the corners round - I think I like that better. Here's a snippet from +A
![all-round](https://user-images.githubusercontent.com/766467/32250790-43d6d108-be64-11e7-82cf-547436f32028.png)
I definitely like the rounded corners better.

**Comment by sslHello** [comment]
We should discuss which design we do prefer.

**Comment by infosecdad** [comment]
In general, I prefer the rounded corners, but the overall theme of the document is mostly square corners.  I propose we make all the boxes with square corners to be consistent throughout the document.

**Comment by Neil-Smithline** [comment]
All corners round per our discussion yesterday
