### ISSUE TITLE
A1: Consider adding reference to "OAT-014: Vulnerability Scanning" to the "How do I prevent" section

### ISSUE THREAD

**Issue by sumitagarwalusa** [OWASP/Top10#256]
In the "Security Weakness" section of "A1 Injection", the text explains that "Injection flaws are easy to discover when examining code. Scanners and fuzzers can help attackers find injection flaws."

It may be helpful to consider whether *preventing* scanners and fuzzers from operating (or at least being aware they are being used) might be a useful technique for the "How do I prevent Injection" section. Currently, the "How do I prevent section" does not address this point from the "Detectability" section.

The OWASP Automated Threat Handbook addresses some of this topic under "OAT 014 Vulnerability Scanning" and offers advice which could be implemented not only by application developers but also by network security teams. This may allow a larger set of defenders (application developers as well as network security teams) to contribute to mitigating this problem.

In addition, "CWE 799 Improper Control of Interaction Frequency" could be added to the "external references" section if deemed helpful/suitable.

**Comment by clerkendweller** [comment]
Whatever the outcome of this issue is, if the automated threat of **Vulnerability Scanning** is mentioned, please use its correct identifier **OAT-014** (the first digit has been reserved for future use, so all current web application automated threats begin OAT-0).

**Comment by Neil-Smithline** [comment]
I never saw the OWASP Automated Threat Handbook before, it's a nice document. Is there a web version of it? All I could find is the PDF.

**Comment by clerkendweller** [comment]
You are correct, there isn't a web version of the document but there should be. We are just getting v1.2 created, and will develop matching wiki pages for all the threats and countermeasures.
