### ISSUE TITLE
GM - Forward

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#257]
"We have taken steps in this release to firm up the definition of issues, and improve the recommendations to be leading practices that may be adopted as an application security standard that covers off around 80-90% of all common attacks and threats." -> kind of fuzzy.  Perhaps reword?.  I think the use of long sentences shorter sentences is better (this is a recurring theme I found in other areas of the document as well).

"What's next for application managers", which is suitable for application owners. -> and "What's next for application managers" which is suitable for application owners.

"Leverage your organization's existing strengths to do and measure what works for you." ->  Perhaps implement or "to do what works for you".  If we are going to suggest measuring security / security metrics, then we should link to some solid application security metrics (a possible idea for another OWASP Top 10 project - OWASP Top 10 Application Security Metrics :)).

"You can find OWASP Top 10 project and translations here" -> "You can find the OWASP Top 10 project and translations here"

"Dave Wichers and Jeff Williams" -> "Dave Wichers and Jeff Williams,"

In the what's next titles, stick to one way of writing it.  I would suggest the title as is (which is what you did in the Introduction section), so:

"What's next for developers" -> "What's Next for Developers"

"What's next for testers" -> "What's Next for Testers"

"What's next for organizations" -> "What's Next for Organizations"

"What's next for application managers" -> "What's Next for Application Managers"

**Comment by vanderaj** [comment]
All of this has now been actioned in the PPTX. Any further improvements will be post GM
