### ISSUE TITLE
GM - Introduction

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#258]
You mention 515 individuals in the beginning and then 516 individuals later on.  I would just mention hundreds of individuals or over 500 individuals.  No need for an exact number.

"This major update adds several new issues, including two issues selected by the community - A8:2017-Insecure Deserialization and A10:2017-Insufficient Logging and Monitoring. Community feedback drove the collection of the most amount of data ever assembled in the preparation of an application security standard, and so we are confident that the remaining 8 issues are the most important for organizations to address, particularly the A3:2017-Sensitive Data Exposure in the age of the EU's General Data Protection Regulation, A6:2017-Security Misconfiguration especially around cloud and API services, and A9:2017-Using Components with Known Vulnerabilities, which can be especially challenging for those on modern platforms, like node.js."

Perhaps reword.  The 2nd sentence is really really long and somewhat confusing.  Also, mentioning that just 8 issues are the most important for organizations to address undermines the other 2 issues.  The focus on A3, A6 and A9 I think is better left to the individual sections.  Here is a possible alternative:

"This major update adds several new issues, including two issues selected by the community - A8:2017-Insecure Deserialization and A10:2017-Insufficient Logging and Monitoring. Two key differentiators from previous OWASP Top 10 editions are the substantial community feedback in addition to the extensive data assembled from dozens of organizations (possibly the largest amount of data ever assembled in the preparation of an application security standard).  This provides us with additional confidence that the new OWASP Top 10 addresses the most urgent application security issues currently facing organizations."

"OWASP is maintaining and promoting" -> "OWASP maintains and promotes"

"In many cases, the most cost-effective approach for finding and eliminating these weaknesses is human experts armed with good tools." -> I would add: "Relying on tools alone provides a false sense of security and is not recommended."

"more diverse collections of vulnerability data yet collected publicly" -> sounds odd, especially the "yet collected publicly" part

"from their efforts" -> "for their efforts"

"out there that will translate" -> "out there who will translate"

**Comment by Neil-Smithline** [comment]
@vanderaj I've done many of the changes suggested, but didn't want to tweak the first paragraph of the introduction without getting your opinion. 

Osama suggest that we basically dump the current first paragraph for two reasons. First, it has a massively long run-on sentence, and, while he didn't directly say it, it seems odd to mention some of the top 10 as being more important than others. He suggests we rewrite the first paragraph as : 

> This major update adds several new issues, including two issues selected by the community - A8:2017-Insecure Deserialization and A10:2017-Insufficient Logging and Monitoring. Two key differentiators from previous OWASP Top 10 editions are the substantial community feedback in addition to the extensive data assembled from dozens of organizations (possibly the largest amount of data ever assembled in the preparation of an application security standard). This provides us with additional confidence that the new OWASP Top 10 addresses the most urgent application security issues currently facing organizations.

You good with that change?

**Comment by vanderaj** [comment]
I'm happy with that change. Please go ahead
