### ISSUE TITLE
GM - Release Notes

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#259]
SAST -> add a link to the OWASP page on them for users who aren't familiar with SAST - https://www.owasp.org/index.php/Source_Code_Analysis_Tools

applicationss -> applications

516 peer submissions -> again, is it 515 or 516?  Do we need an exact number?

"Over the last decade, and in particularly these last few years, the fundamental architecture of applications has changed significantly" -> "Over the last decade, and particularly in the last few years, the fundamental technology and architecture of applications has changed significantly"

I changed it to technology + architecture because JavaScript which is mentioned isn't a new architecture

Also, I would reorder this section with the most important first.  I would have them in this order (I split one of them into two)

Microservices
APIs exposing old code
SPAs
JavaScript

"Microservices written in node.js and Spring Boot are replacing older enterprise service bus applications using EJBs and so on. Old code that never expected to be communicated with directly from the Internet is now sitting behind an API or RESTful web service. The assumptions that underlie this code, such as trusted callers, are simply not valid." -> I would split this into the following:

Microservices written in node.js and Spring Boot are replacing traditional monolithic applications (I removed enterprise service bus as I think message queues are a more direct replacement for the enterprise service bus).  Microservices comes with their own security challenges including establishing trust between microservices, the use of container technology, secrets management, etc.

Old code that never expected to be communicated with directly from the Internet is now sitting behind an API or RESTful web service to be consumed by SPAs and mobile applications.  The assumptions that underlie this code, such as trusted callers, are no longer valid.

"Single page applications, written in JavaScript frameworks such as Angular and React, allow the creation of highly modular front end user experiences, not to mention the rise and rise of mobile applicationss using the same APIs as single page applications." -> "Single page applications, written in JavaScript frameworks such as Angular and React, allow the creation of highly modular feature-rich front ends.  This means that functionality that has traditionally been delivered server-side is now being moved client-side, which brings its own security challenges."

* I removed the mention of mobile applications and SPAs using APIs as it was already mentioned in the Old code section

"JavaScript is now the primary language of the web. node.js and modern web frameworks such as Bootstrap, Electron, Angular, React amongst many others, means source that was once on the server is now running on untrusted browsers." -> I think this point mixes two issues.  I moved one up to the SPA section (more functionality is running on the client) and would leave this just about JavaScript.  So I would suggest:

"JavaScript is now the primary language of the web with node.js running server side and modern web frameworks such as Bootstrap, Electron, Angular, and React providing on the client."

Suggestion: perhaps add a bullet on DevOps emphasizing that security has to be built in from the start?

"A8 CSRF. Less than 5% of the data set supports CSRF today, which places it around #13" -> can add that this is probably due to good framework support for protecting against CSRF

**Comment by sslHello** [comment]
Added links to SAST and DAST on pages: RN, A1, A4, A5, A10

**Comment by vanderaj** [comment]
I've accepted nearly all of these, but due to space reasons I had to collapse microservices and old code, and tighten up the language. There was no room for the DevOps commentary, so that will have to be left out. Any further QA on this item will have to be post GM
