### ISSUE TITLE
GM - Risk - Application Security Risks

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#260]
OWASP Risk Rating Methodology -> Add link: https://www.owasp.org/index.php/OWASP_Risk_Rating_Methodology

"In this edition, we have changed the risk rating system around compared to previous version to assist with our ranking of likelihoods and impacts." -> "In this edition, we have change the risk rating system to assist in calculating the likelihood and impact or any given risk."

"It is critical that you apply your custom threat agents and business impacts based upon the data asset criticality." -> "custom threat agents" is almost never used as a phrase (only 4 hits on Google).  Instead, "It is critical that you customize risk based on your specific threat agents and business impacts."

I think referring users to +R Note About Risks to understand how risk was calculated is a good idea that should be added

**Comment by infosecdad** [comment]
Appreciate the review and feedback, appropriate changes have been made.
