### ISSUE TITLE
GM - A1:2017 Injection

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#262]
"Almost any source of data can be an injection vector, including users, parameters, external and internal web services, and all types of users." -> you mentioned users twice and I think this can be clarified.  Instead: "Almost any source of data can be an injection vector including any user-supplied data.  Users can be both application users as well as services and processes such as external and internal web services."

"expression languages, ORM queries" -> "expression languages and ORM queries"

"Hostile data is used within ORM search parameters such that the search evaluates out to include sensitive or all records." -> "search evaluates out" sounds strange.  Instead: "Hostile data is used within ORM queries that accept unsanitized input parameters."

"Organizations can include SAST and DAST tooling into the CI/CD pipeline to alert if existing or newly checked in code has injection prior to production deployment." -> I would have this as the last sentence in the paragraph as it is specific to organizations that have CI/CD pipelines.  Also, "has injection prior" -> "is vulnerability to injection attacks"

"Preventing injection requires keeping data separate from commands and queries." -> "Preventing injection requires keeping data separate from commands and queries.  A number of options can be used:"

"ORMs or Entity Framework" -> Entity Framework is an example of an ORM.  So I would drop it and just have "use ORMs."

"NB: When parameterized, stored procedures" -> "NB: Parameterized stored procedures"

Java Encoder is mentioned here although A1 does not cover XSS

I would consider removing the Portswigger link at the end of the page as it may be modified in the future: https://portswigger.net/knowledgebase/issues/details/00101080_serversidetemplateinjection

**Comment by Neil-Smithline** [comment]
Thanks again Osama. Regarding PortSwigger, we've decided to leave the reference in place. We've had some communication with PortSwigger, while they didn't commit to never moving the page, they said they don't foresee it moving. And it is a good reference to material not covered elsewhere in the document.
