### ISSUE TITLE
GM - A6:2017 Security Misconfiguration

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#267]
Under "How to Prevent?, I would add:

Maintain a repository covering all components of your application stack and monitor for reported vulnerabilities to all components.

"Attacker discovers" -> "An attacker discovers"

"to find file" -> "to find files"

"Attacker then finds" -> "The attacker than finds"

**Comment by sslHello** [comment]
@ossie-git - Thank you for your suggestions.
I've edited the scenatios section with reference to your suggestions, see commit 5974c5e. I'd like to link this issue with #182 (revision of examples).
Well, I'd say that the suggestion for 'How to Prevent' machtes better to A9. The second bullet should contain this. 
Cheers Torsten

**Comment by sslHello** [comment]
Updated 'How to Prevent' in Commit cc890f3.
Rephrased the text linking to A9, this should fix this issue, too.
