### ISSUE TITLE
GM - A7:2017 Cross-Site Scripting (XSS)

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#269]
Is the Application Vulnerable?

"or there is no content security policy (CSP) header" -> I would remove this as it is already mentioned in the "How to Prevent" section.  Preferably we want to drive developers to use CSP as a backup control, not as the primary control (which is the approach endorsed in the How to Prevent section)

"Typically the user will need to interact with a link, or some other attacker controlled page, such as a watering hole attack, malicious advertisements, or similar." -> "Typically the user will need to interact with some malicious link that points to an attacker-controlled page."

How to Prevent?

"Use safer frameworks that automatically escape for XSS by design, such as in Ruby 3.0 or React JS, or leverage framework XSS protections." -> I would change it to the following: "Use safer frameworks that automatically escape for XSS by design, such as in Ruby 3.0, Angular or React JS, or leverage framework XSS protections.  This frameworks typically cover the most common XSS scenarios but not all of them.  Ensure that you know the limitations of each framework's XSS protection and handle the use cases which are not covered."

Same comment on the PortSwigger articles as before

**Comment by sslHello** [comment]
Hi  ossie-git,
thank you. 
I've tried to adopt as much as space had been available. Sorry, for 'How to Prevent' this were only some words: 'But take care about their limitations.'
**TBD:** Discuss about links to PortSwigger (I'll label this issue for the next Discussion)
Cheers Torsten

**Comment by ameft** [comment]
I believe there's a small error in the last RC2 in the "How Do I Prevent This?" paragraph.
Ruby 3.0 doesn't exist (version 2.4 is the latest), I believe the writer wanted to refer to Ruby on Rails 3.0 (Ruby is the general language, Ruby on Rails is a specific web framework), which started to automatically escaping unsafe input. Moreover RoR 3.0 is from august 2010, so we can now simply refer to just Ruby on Rails safely I believe.
Also React JS should be React.js (old) or simply React as it's called nowadays.

**Comment by infosecdad** [comment]
Have addressed the feedback, thanks!
