### ISSUE TITLE
A10 Unprotected API subject is vague and confusing

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#27]
In new modern days of testing web applications, APIs are part of web applications and should not be considered as separate pieces. For example we see a lot of websites these days that can be a simple HTML pages using extensive APIs.
IMHO practically it is wrong to say unprotected API as a separate subject. API on its own can be vulnerable to any of the OWASP top 10 for example. So if we find one issue on an API, shall we say it was an unprotected API? Or this is only related to access control issues (A4) but for the APIs?
Additionally, who will decide what is an API and what is a web application? Shall we consider anything that doesn’t include HTML in their responses APIs? Or shall we work this out using the requests or perhaps if we have a restful application only? These days many of the APIs can be like a normal web page and response differently depends on the request. 
Soroush Dalili

**Comment by jmanico** [comment]
I politely disagree. API's are becoming part of organizations •data infrastructure• serving •multiple apps• and have massive impact beyond one app when vulnerable. API's are also key parts of AuthN, AuthZ and crypto services in mature orgs.

API's are special and getting more special. I personally like this category.

--
Jim Manico
@Manicode

**Comment by Neil-Smithline** [comment]
Including @irsdl.

**Comment by Neil-Smithline** [comment]
Based on the results of the industry survey ([background on survey](https://owasp.blogspot.com/2017/08/owasp-top-10-2017-project-update.html)), API vulnerabilities will not be in the Top-10. Where appropriate, mentions of API vulnerabilities will be added to other risks.
