### ISSUE TITLE
GM: +A: What's next for Application Managers

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#274]
"We suggest establishing application owners and application managers for every application to provide accountability, responsibility, consulted and informed (RACI), to ensure the organization who can sign off risks, and who is responsible for security design, building, testing and deploying application security." -> Not very clear.  I get the point but I think it can be re-worded

"rough planning" -> not sure why you mentioned rough

**Comment by sslHello** [comment]
Hi Ossie-git,
yes, I'd like to rephrase it compleately.
What do you think about:
"We suggest establishing the role of application managers as technical counterpart to the application owner. He is in charge of the whole application lifecycle from IT perspective from collecting the requirements until the process of retiring systems, which is often overlooked. 
He should ensure that the following is performed:"
(I hope the middle phrase did not get too long, perhaps it should be split).
Later I'd like to delete sentences like "To ensure applications have a secure design, the following should be performed:". So we can shorten some of the following paragraphs.
What do you think?
Cheers Torsten

**Comment by vanderaj** [comment]
Torsten, I've reviewed the page and deleted the additional text. I've fixed the personal pronoun "he" to be the application manager, because it could also be a she. I've fixed up the text in Markdown and PPTX.
