### ISSUE TITLE
What are the stats on SSRF and others?

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#28]
With having all cloud services and lots of solutions to host different resources on different servers, we see more SSRF attacks these days with which attackers can target another server or another internal port and so on. I thought we should see SSRF now in OWASP top 10 but you have all the stats so it might be good too.

Soroush Dalili

**Comment by jmanico** [comment]
SSRF may be worth rolling under API security if it stays.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by vanderaj** [comment]
Soroush Dalili,

The data will be published to Github shortly. In short, it's not even close to being Top 10 material. 1.69% of 114,000 apps have it, and it's number 28. We know the impact is really high from SSRF, and for that 1 in every 50 apps that have it, it's terrible, but it's not OWASP Top 10 material. 

thanks
Andrew
