### ISSUE TITLE
Ack - Finalize Acknowledgements

### ISSUE THREAD

**Issue by Neil-Smithline** [OWASP/Top10#280]
The formatting can use a bit of tweaking, and I also want to update the list of users with the latest list. Perhaps as of Golden Master date.

**Comment by infosecdad** [comment]
The list of companies was updated and sorted, we just need to updated the github list before release.

**Comment by Neil-Smithline** [comment]
I have moved to multi-column text boxes instead of tables to improve the look of the page. This also made the data contrib and indiv contrib look similar.

**Comment by Neil-Smithline** [comment]
@infosecdad - The list of data contributors needs a final going over by you. I've found at least two, "Company" and "Web", that seem wrong. I looked to find the raw data as to who has provided, but couldn't. So I'm reassigning this issue to you. The problem is in both GitHub and PPTX.

**Comment by infosecdad** [comment]
Company and Web are both correct, I double checked.

**Comment by Neil-Smithline** [comment]
Converted them to "Company.com" and "Web.com"
