### ISSUE TITLE
A few questions/clarifications/additions

### ISSUE THREAD

**Issue by nickthetait** [OWASP/Top10#281]
# (all pages)
## References
Any of the OWASP links are listed under a mini OWASP heading/category, so it seems unnecessary that they each include OWASP in the URL's name.

# A1
## How Do I Prevent Injection?
Bullet points 1 and 3 mention "NB". I've got no idea what this means.

# A9
## Am I Vulnerable to Known Vulnerabilities?
Bullet point 4 states "This is likely the root cause of one of the largest breaches of all time."
Not everyone will know which event is being referenced. Especially after an even larger breach (inevitably) occurs :sweat:
 
## Example Attack Scenarios
Concluding paragraph says "There are automated tools to help attackers..." but it might be nice to point out that defenders can use these tools too :smile: 

I have a background in software development but am a relative newcomer to cybersecurity, would just like to add that the Top10 document made sense to me and provided significant value. :+1:

**Comment by infosecdad** [comment]
Thank you for your feedback, it has been incorporated where appropriate. Welcome to InfoSec, best wishes!
