### ISSUE TITLE
+O What's Next for Organizations

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#284]
Received by mail from Thomas:

- Get started: '• Document all applications and associated data assets in a  Configuration Management Database (CMDB).' -> '• Document all applications and associated data assets. Larger Organizations should think about a Configuration Management Database (CMDB) for this purpose.'

Thank you.
Cheers Torsten
PS: I'd suggest: 'Larger Organizations should consider to use a Configuration Management Database (CMDB) for this purpose.' if we do have enough space.

**Comment by vanderaj** [comment]
Resolved
