### ISSUE TITLE
Should we implement an edition number?

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#285]
Should we implement an edition number to track smaller changes, e.g, links?

**Comment by vanderaj** [comment]
I'm not sure what this is in relation to? Is this about post-release changes? Generally we haven't touched post release text, but if you're thinking something like OWASP Top 10 2017 (lang) 1.0a 1.0b etc are we likely to do this?

**Comment by infosecdad** [comment]
The thought was if we decided to perform maintenance on links or similar that there is a chance at mid-cycle revisions.  It's not something that has to be done now though, we can add it in the future if needed.
