### ISSUE TITLE
Paragraph style: justification, or left oriented?

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#286]
Which paragraphs should be in justification which left oriented?

**Comment by Neil-Smithline** [comment]
They all should be left justified (probably what you meant when you said "left oriented"). None of them should be "full justified" (where both left and right margins line up). I've fixed a bunch of these paragraphs in the introduction. If there are no more that you know of, we can close this issue.

**Comment by vanderaj** [comment]
Left. Just do it, let's get it out the door.

**Comment by infosecdad** [comment]
Closing at this point, I don't see any more that aren't left justified.
