### ISSUE TITLE
RN: SAST, add subtitle 'Merged'

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#297]
'SAST' -> 'static source application tests (SAST)'

'**Retired, but not forgotten**
* A4 ... and A7 ...
* A8 ...
* A10 ...'
=>
'**Merged**
* A4 ... and A7 ...

**Retired, but not forgotten**
* A8 ...
* A10 ...'

**Comment by Neil-Smithline** [comment]
Torsten - there's no room for adding the merged header. The page is already full. I didn't want to close it without fixing, so I'm reassigning it to you in case you want to try to find some space. If not, just close it.

**Comment by vanderaj** [comment]
The first use of SAST on page 5 not only spells this out, it has a link to what SAST tools are. So I'm closing this pre-emptively.

**Comment by sslHello** [comment]
SAST is OK,
I see that we have now less space, so should we change:
* 'Retired, but not forgotten' -> 'Merged or retired, but not forgotten'
* Add a colon to all sub-haeders like this?

**Comment by Neil-Smithline** [comment]
Done!
