### ISSUE TITLE
A1: delete XML (parsers)?, ORM, Scenario2: add 'delete'

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#300]
- Verify if we still need XML parsers, XML data input etc besides A4-XXE
- Add 1 x long words for ORM
- Scenario 2: 'dangerous attacks could modify data or even' -> 'dangerous attacks could modify or delete data, or even'

**Comment by Neil-Smithline** [comment]
Torsten - 
> Verify if we still need XML parsers, XML data input etc besides A4-XXE

I think that the reference still makes sense. XXE is an XML-specific problem that is managed by tightening the configuration while injection is a problem with any interpreter that is fixed with input validation and escaping. 

> Add 1 x long words for ORM

Torsten - what do you mean by this?

> Scenario 2: 'dangerous attacks could modify data or even' -> 'dangerous attacks could modify or delete data, or even'

I made this change.

**Comment by Neil-Smithline** [comment]
Ah - you meant spell out the acronym's meaning - got it!

**Comment by jmanico** [comment]
I agree XXE is more of a configuration or access control issue as opposed to injection, FWIW.
