### ISSUE TITLE
Generated risk table is incorrect

### ISSUE THREAD

**Issue by vdbaan** [OWASP/Top10#314]
The table uses | <pipe> symbol between  elements Prevalence 2 \| Detectability 3

When using pandoc this pipe symbol is not escaped and used as column delimiter which does not format well on both the pdf and docx file.

**Comment by vanderaj** [comment]
I'm going to change these to a colon, as I agree, it's not great.

**Comment by vanderaj** [comment]
@vdbaan Please check now, but I think I've fixed it in all A1..A10. Did it appear anywhere else?
