### ISSUE TITLE
additional spaces in documents

### ISSUE THREAD

**Issue by vdbaan** [OWASP/Top10#315]
in 0x06-release-notes.md:
between and and removing in the following sentence:
"After over 500 peer submissions, and  removing issues"

in 0xa3-sensitive-data-disclosure.md:
between smtp and the comma

in 0xb3-next-app-mgrs.md:
between non and functional in the sentence:
"Compile the technical requirements including functional and non functional security requirements"

**Comment by Neil-Smithline** [comment]
The last two were already fixed so there's only one commit.

Thanks!
