### ISSUE TITLE
Space missing in documents

### ISSUE THREAD

**Issue by vdbaan** [OWASP/Top10#317]
In 0xa6-security-misconfiguration.md:
there should be a space between to and all in the sentence:
"A task to review and update the configurations appropriate toall security notes"

in 0xc0-note-about-risks.md:
there should be a space between the and OWASP in the sentence:
"The Risk Rating methodology for the Top 10 is based on theOWASP Risk Rating Methodology"

**Comment by Neil-Smithline** [comment]
Someone beat me to the 0xa6 one  so there's only one commit.

Thanks again @vdbaan!
