### ISSUE TITLE
Fix ModSecurity project name(s) in A10

### ISSUE THREAD

**Issue by dune73** [OWASP/Top10#319]
@ossie-git fixed the wording of the ModSecurity section in A10. Much better now. However the project names are still not correct.

Is: "... web application firewalls such as mod_security with the OWASP Core Rule Set."
Should be: "... web application firewalls such as ModSecurity with the OWASP ModSecurity Core Rule Set."

These are the official titles of the two projects.

**Comment by Neil-Smithline** [comment]
Thanks!
