### ISSUE TITLE
rename "app" and "apps" to application/applications

### ISSUE THREAD

**Issue by securestep9** [OWASP/Top10#320]
Ref: #243 

New instances of the word "app" have emerged in the document.

Several changes should be made to give the document more professional style. 
The only acceptable case to use the word "app" is in the context of a "mobile app" or "smartphone app" .

List of changes to do:

Page 6: _"Frameworks commonly include CSRF defenses, with < 5% of all **apps**, now #13."_ -> change to "applications". 

Page 9: ..._"and is present in all stateful **apps**"_  -> change to "applications". 

Page 13: _"The **app** server’s configuration allows detailed error messages"_  -> change to "application". 

Page 14: "_The application server comes with sample **apps** that are not removed from your production server. These sample **apps** have known security flaws attackers use to compromise your server. If one of these **apps** is the admin console, and default accounts weren’t changed the attacker logs in with default passwords and takes over."_ -> change to "applications". 

 Page 20: _"gain insight and improve security across their **app** and API portfolio."_  -> change  to "application"

**Comment by sslHello** [comment]
'+R': Threat Agents: changed 'App' to 'Application', deleted App at Business Impacts:
![grafik](https://user-images.githubusercontent.com/7883438/32984916-d42c724a-ccaf-11e7-89b1-139032d54873.png)

**Comment by sslHello** [comment]
Thanks for the feedback. I believe I've gotten most of them. Due to space constraints some could not be changed, e.g. 'App. Specific'
