### ISSUE TITLE
Where is malicious file upload?

### ISSUE THREAD

**Issue by Gilc83** [OWASP/Top10#322]
Hi
As a vetarn penteseter for the last 13 years, it always bother me that malicious file upload is not mentioned in OWASP top 10. Webshell are devistating attacks, malicious file upload can be used as XSS if you upload HTML files, and even "just" Office file upload may result in files that include Macro and other "fun" stuff.
This vulnerability is hard to detect using SAST and even PT, but I believe it is not getting the attention is deserves. It wasn't even part of the community questineer, although I wanted to vote for it.

**Comment by jmanico** [comment]
Gil,

While it's a little late in the game for a new addition, I think your
comment is spot on. It's also a painfully difficult feature for
developers to code in a secure fashion. This is something we certainly
should consider for the Top Ten 2020.

**Comment by infosecdad** [comment]
When an application has the functionality to upload a file, it can be difficult to properly handle.  There is very little data on it and I think it's probably a combination of a smaller number of applications that allow file upload and the difficulty in finding in an automated fashion.  It's on the list of additional risks to consider and will most likely be part of the 2020 survey.
