### ISSUE TITLE
Clarify the term "SPAs" in section "What changed from 2013 to 2017?"

### ISSUE THREAD

**Issue by securitybits** [OWASP/Top10#327]
I assume that the term SPAs in "Old code never expected to be communicated with directly from the Internet is now sitting behind an API or RESTful web service to be consumed by SPAs and mobile applications." refers to single-page applications, but it would be good define this term on first use. Notably the bullet under this writes it out, but I thing it should be defined on first use, e.g., SPA (Singe-Page Application), and then it can be abbreviated to SPA. Also, I would prefer to write it with the hyphen (as Wikipedia does) to emphasize that it's a single-page application and not a single _page_ application.

**Comment by infosecdad** [comment]
Thanks, updated per feedback.
