### ISSUE TITLE
Conflicting description of CSRF prevalence in section "Retired, but not forgotten"

### ISSUE THREAD

**Issue by securitybits** [OWASP/Top10#329]
Regarding CSRF it states "Commonly include CSRF defenses, with < 5% of all apps, now 13.", however it seems misleading when looking at the underlying data. From the next bullet talking about place 25, it seem that this number indicates the prevalence as that matches the frequency chart for unvalidated forward, but place 13 is in that case incorrect for CSRF.

The incidence rate tab has CSRF as 5% of the total number of findings but at 23% if you average the percentage of each data set (mainly due to Veracode not really finding this issue at all, and their number of data being so large compared with the others). If we stick with the first way of counting this, at 5%, it would be on place 10 and not 13. If we use the other average of 23%, it would be place 11 (as the average for other findings goes up even more in some instances). Place 13 doesn't seem right in any of these.

**Comment by infosecdad** [comment]
Addressed in the commit to issue #330
