### ISSUE TITLE
False statement about A10 in section "Retired, but not forgotten"

### ISSUE THREAD

**Issue by securitybits** [OWASP/Top10#330]
The last bullet says "A10-Unvalidated Redirects and Forwards, less than 1% of the data set supports this issue today, now 25" which is plain wrong and a misreading of the data set. While it's correct that _Unvalidated Forwards_ are less than 1% on place 25, A10 in 2013 also included _Unvalidated Redirects_ (noted as Unchecked Redirect in the data set), and this has a prevalence of nearly 9%, putting it on place 6 and not 25.

**Comment by infosecdad** [comment]
Thanks for the catch, updated the verbiage.
