### ISSUE TITLE
Confusing arrows in graphic comparing 2013 vs 2017

### ISSUE THREAD

**Issue by securitybits** [OWASP/Top10#331]
The arrows between 2013 and 2017 in the graphic comparing the two versions can be misleading at first sight. Since they are positioned next to the start of the 2017 table, and with matching color, the first impression is that they show how the new entry has changed, e.g.., move up or down. In fact it represents the old entry, e.g., the 'down arrow' next to A3:2017 doesn't mean that this item now lower as it first looks like (in fact it's much higher), instead it's representing the movement of the old A3:2013 (XSS) to the left. 

I suggest that at least the color of the arrows are changed to match the 2013 list (green) as that's what they relate to, or that a more elaborate change is made to the table to clarify what it's trying to say.

**Comment by Neil-Smithline** [comment]
As we're only hours before release, a more elaborate change is not possible for anything other than a show-stopper. But we may be able to change the color. 

@sslHello - do you have any thoughts on this? If you agree with the change, how important do you think it is?

**Comment by Neil-Smithline** [comment]
Another alternative would be to make the arrows a neutral color, gray or something.

**Comment by Neil-Smithline** [comment]
@securitybits - after some conversation and a few trials, we decided to go with a neutral gray. 

<img width="617" alt="gray" src="https://user-images.githubusercontent.com/766467/32957661-5d4a05a0-cb8a-11e7-97c9-bc2e3c1bd733.png">

**Comment by securitybits** [comment]
Yes, that looks better, thanks for updating this!
