### ISSUE TITLE
Clarify that the scope is web application risks in "What's My Risk"

### ISSUE THREAD

**Issue by securitybits** [OWASP/Top10#332]
This statement is somewhat misleading "The OWASP Top 10 focuses on identifying the most serious risks for a broad array of organizations" as it's not general risks for an organization but more specifically web application security risks. A possible clarification could be "The OWASP Top 10 focuses on identifying the most serious _web application security_ risks for a broad array of organizations" or "The OWASP Top 10 focuses on identifying the most serious _security_ risks _in web applications_ for a broad array of organizations".

**Comment by infosecdad** [comment]
Thanks for the recommendation, provided clarification.
