### ISSUE TITLE
Suggested change to reference of CWE in "What's My Risk"

### ISSUE THREAD

**Issue by securitybits** [OWASP/Top10#333]
I think that 'security practices' should be replaced with 'naming conventions' in the sentence "Where possible, the names of the risks in the Top 10 are aligned with Common Weakness Enumeration (CWE) weaknesses to promote generally accepted _security practices_ and to reduce confusion" - and please add a full stop at the end of the sentence too.

**Comment by Neil-Smithline** [comment]
I agree. Change made.
