### ISSUE TITLE
Missing unauthorized data exposure in impact of A1 Injection

### ISSUE THREAD

**Issue by securitybits** [OWASP/Top10#337]
The impact is described as "Injection can result in data loss or corruption, lack of accountability, or denial of access. Injection can sometimes lead to complete host takeover. The business impact depends on the protection needs of your application and data." - I think this fails to highlight one of the main impacts of many injection attacks, e.g., data disclosure to unauthorized entities. For example, one of the typical impacts of SQL injection is that you can dump data from the DB.

**Comment by Neil-Smithline** [comment]
Thanks!
