### ISSUE TITLE
T10: Should we keep apart the Summary about Risks from 'How to Prevent'?

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#339]
Should we reword this summaries more as a risk?
A3: "Sensitive data deserves extra protection, such as encryption at rest or in transit, as well as special precautions when exchanged with the browser."
A6: "Not only must all operating systems, frameworks, libraries, and applications be securely configured, but they must also be patched/upgraded in a timely fashion." -> "Not only this concernes all operating systems, frameworks, libraries, and applications be securely configured, but also their configurations might get out of date and insecure over time or with new patches and upgrades."

**Comment by Neil-Smithline** [comment]
I went with this text - I think it gets most of what you suggest:
> Sensitive data may be compromised without extra protection, such as encryption at rest or in transit, and requires special precautions when exchanged with the browser.

As far as the A6 change, I think that what we have is good and shouldn't be changed.
