### ISSUE TITLE
A7: some suggestions

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#344]
Is the Application Vulnerable:
- 'Reflected XSS: Your application' -> 'Reflected XSS: The application'
- 'Ideally, your application would not send attacker-controllable data to unsafe JavaScript APIs.' should be at 'How to Prevent' (if we can obtain any space)

How to Prevent:
'Escaping untrusted' -> 'Normalizing and escaping untrusted ...' 
or -> 'Escaping including normalizing untrusted ...'

**Comment by Neil-Smithline** [comment]
I changed "your" to "the. I didn't make the other changes as there's not room (even adding "normalizing" adds a line)
