### ISSUE TITLE
A9: risk-based timely fashion / patch management process

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#345]
Is the Application Vulnerable?
- 'If you do not fix or upgrade the underlying platform, frameworks, and dependencies in a timely fashion.' -> 'If you do not fix or upgrade the underlying platform, frameworks, and dependencies in a risk-based timely fashion. '
- Should we add something like: 'If software developers don't test the compatibility and release their software to be used with updated or upgaded versions of the other components.'

How to Prevent
- 'Software projects should have a process in place to:' -> 'There should be a patch management process in place to:'

**Comment by Neil-Smithline** [comment]
For the second bullet, I went with "If software developers do not test the compatibility of updated, upgraded, or patched libraries.". Adding the bit about releasing seems to be repeating what's said elsewhere.

**Comment by Neil-Smithline** [comment]
Fixed with 22714c5
