### ISSUE TITLE
+O: smaller suggestions

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#348]
- Add a link to 'OWASP SAMM'
- 'Define a common set of reusable security controls that complement these policies and standards and provide design and development guidance on their use.' -> 'Define a common set of reusable security controls that complement these policies and standards, document their relation and provide design and development guidance on their use.'
- Add the [Application Security Guide for CISOs](https://www.owasp.org/index.php/Application_Security_Guide_For_CISOs) where appropriate

**Comment by vanderaj** [comment]
Torsten, I'm not sure I understand the second change. Can you explain to me what you're after here. I've done the other two.

**Comment by Neil-Smithline** [comment]
I believe that Torsten is suggesting that we add text that states that we document the relationship (he said "relation") between security controls and the policies and standards. I'm not sure that such text is needed.

**Comment by vanderaj** [comment]
I've re-read this several times with the change in place, and it doesn't make sense. I'm not going to execute the second change. I know what he was aiming for (requirements traceability from policies / standards to implementation), but I couldn't figure out a way to make that fit in a reasonable size. Let's circle back about this issue in 2020, as I think we will have a far better solid understanding of SSDLC processes at that point that is not rooted in waterfall stage gates.
