### ISSUE TITLE
Risk: add an OWASP Reference?

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#354]
Should we add the [OWASP Threat Dragon](https://www.owasp.org/index.php/OWASP_Threat_Dragon)?

**Comment by drwetter** [comment]
I would suggest to make it dependent on the status so that people don't spend time looking into something which isn't mature enough.

Catch is: It has no status. :(

**Comment by vanderaj** [comment]
It's an incubator product, so I'd say no. If it was a Lab or Flagship, then yes. I'll wait 1 day and close this unless there's a strong argument

**Comment by sslHello** [comment]
Yes, I see. It's a pitty ....
