### ISSUE TITLE
A3: Restructure sentence in "Scenario #2" of Example Attack Scenarios

### ISSUE THREAD

**Issue by securitybits** [OWASP/Top10#359]
I suggest the sentence "An attacker monitors network traffic, strips the TLS (e.g. at an open wireless network), intercepts requests, and steals the user's session cookie." is changed to "An attacker monitors network traffic (e.g. at an open wireless network), downgrades connections from https to http, intercepts requests, and steals the user's session cookie."

**Comment by drwetter** [comment]
Sounds better, yes.

Two bits: 

*open* wireless network insinuates that it has to be not encrypted at all to mount an attack. This is unfortunately wrong. Even with PSK the encryption is derived from the PSK. Additionally  we'll see probably a long time wireless devices which haven't been patch against KRACK.

So 1) I would suggest to change __open wireless network__ to __not trusted wireless network__.

Then (2): cookie is old school. I would just omit it (__steals the user's session_)

**Comment by Neil-Smithline** [comment]
Definitely an improvement, thanks! 
I went with "insecure wireless network". I also decided to leave cookie in there because it makes sense with the rest of the example. I didn't want to rewrite too much on the eve of release.
