### ISSUE TITLE
A5: Unclear and potentially misleading reference to CORS in "How To Prevent"

### ISSUE THREAD

**Issue by securitybits** [OWASP/Top10#363]
The second bullet states "Implement access control mechanisms once and re-use them throughout the application, including CORS." but it's not clear to me what the reference to CORS here is intended to mean. As CORS is effectively a method to _weaken_ the same-origin policy in a (hopefully) controlled manner, I don't see how applying it throughout the application would make the access control better, it could in fact be the opposite that you unintentionally apply a CORS policy that opens up parts of the application to third-party interaction where it's not intended. 

I think we should either remove the reference to CORS in this bullet, or clarify better what the intention is with the recommendation.

**Comment by Neil-Smithline** [comment]
I think I got better wording on it, now. Please feel free to reopen if you still think it needs improvement. 
> Implement access control mechanisms once and re-use them throughout the application, including minimizing CORS usage.

Thanks for the helpful comments!
