### ISSUE TITLE
A7 Seems like it's promoting WAFs

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#37]
A7 - Insufficient Attack Protection
 - WAF and other blocking detection mechanism will never fully protect against unknown vulnerability. The thing is that they either break your application through aggressive blocking or have bypass when they aren't aggressive. Those products have always been crutches for applications that had poor security or couldn't be updated. Saying that you are vulnerable because you don't have one in place is really misguided. 
 - Incident response is operational concerns. It's not an application security concern. Unless the OWASP Top 10 guide wants to enlarge its scope to more than just application security, this is simply not at the right place. The ASVS guide is probably a better place to introduce this.
 - Patching software is already covered by A5 and A9. The point #1 of "Am I vulnerable to Attack?" of A5 is exactly about that : "Is any of your software out of date?". Perhaps this point should be expanded in A5 or A9 instead.
- The OWASP Top 10 is a general document for application security. It should be about things that apply to almost every web application. I wouldn't recommend that every web application should to lock account automatically. This kind of security measure is a trade-off between usability, security and introducing other security issues (denial of service for example). OWASP Top 10 may recommend evaluating this choice, but I don't think it should pick a side especially since it can have security impact like denial of service (ex.: locking all user account).
 - This category addition really feels like it's been lobbied by the WAF industry as a way to sell more of their product. One of the core values of the OWASP organization is that it shouldn't be a platform for vendors to sell their products. Adding categories that favourably affects some vendor should be weighted more carefully.
8.	Olivier Arteau

**Comment by Neil-Smithline** [comment]
FYI @HoLyVieR

**Comment by vanderaj** [comment]
This risk is going to be removed as per community feedback at the Project Summit, survey data and revised data call. Thank you for your input on this matter.
