### ISSUE TITLE
+A: Consider adding references to additional standards/checklists

### ISSUE THREAD

**Issue by Neil-Smithline** [OWASP/Top10#370]
Per #283, there are perhaps better checklists/standards/templates that we could reference. TSS-WEB (Checklist) https://tss-web.secodis.com/ was mentioned, though I've expressed concerns about it [here](https://github.com/OWASP/Top10/issues/283#issuecomment-345485435).

**Comment by vanderaj** [comment]
I know you allocated this to the 2020 version, but I'd like to close this now. Let's worry about this in 2020.
