### ISSUE TITLE
Near Final Release Minor Issues

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#384]
Hi,

Was looking at: https://github.com/OWASP/Top10/blob/master/2017/OWASP%20Top%2010-2017%20(en).pdf and just saw 2 minor issues:

Foreword:

I think you meant to remove this:

"We hope that the OWASP Top 10 is useful to your application security efforts. Please don't hesitate to contact OWASP with your questions, comments, and ideas at our GitHub project repository:
• https://github.com/OWASP/Top10/issues"

Section A3

The box outline cuts across the last line Graphic Processing Units

**Comment by drwetter** [comment]
yes.

That contradicts the idea that the T10 is where app sec **starts.**

**Comment by Neil-Smithline** [comment]
Fixed A3 in 06012cb

**Comment by Neil-Smithline** [comment]
First, thanks lots for the help, guys!

@ossie-git - I think that we mean to leave GitHub open for future comments. 

@drwetter - I'm not sure what you feel contradicts stating that the T10 is a just a first step. Can you please clarify.

**Comment by drwetter** [comment]
> I'm not sure what you feel contradicts stating that the T10 is a just a first step. 

_We hope that the OWASP Top 10 is useful to your application security efforts._ 

It can be misunderstood that this covers all application security efforts. I know that in other part of the document and even in the foreword you tell this is not the case. However I feel that this sentence points somewhat into another direction and weakens those statements.

Avoid to feed those folks which try to use this for compliance, app sec program, SDLC, pentest to-do, <whatsoever> :-)

My first idea was _We hope that the OWASP Top 10 is useful for your first application security efforts._ but maybe the word _first_ is not good enough for the T10?

**Comment by ossie-git** [comment]
@Neil-Smithline For the first point, I think telling people to leave comments, questions, etc. will drown the GitHub page with issues and questions which I don't think anyone wants.  Also, I think this gives the reader an expectation that their questions / comments, etc will be answered by the OWASP Top 10 team which probably isn't true.  I think this can be removed and if instead you really want to add a channel for users to get help and support each other, you can point them to the OWASP Slack channel instead.

The call for comments when preparing the Top 10 for 2020 can be later on (in 2019/2020) and outside the document.

**Comment by Neil-Smithline** [comment]
Regarding 
> We hope that the OWASP Top 10 is useful to your application security efforts.

Perhaps the wording could be better, but I think that sentence is fine at this point as we're really trying to minimize changes now.

Regarding GitHub issues, I raised this topic with the leads yesterday. This was not the first time we spoke about it. We've still feel that GitHub issues is how we want comments to be made. A big part of our motivation is that we are striving for openness throughout the process. There have been complaints that comments and the responses to previous versions of the T10 weren't public. Our use of GitHub and GitHub issues is an effort to remedy that. We're planning on being responsive to all issues filed. If there's a flood of GitHub issues, we may later regret this decision - let's hope that doesn't happen.

We thank both of you for all of the effort you have put forth on this.

**Comment by drwetter** [comment]
Well guys, thanks for your openness, your work and chewing on all the bits we threw at you. :-)

Finally _the_ flagship project has bodly go where it hasn't gone before!
