### ISSUE TITLE
Hebrew translation

### ISSUE THREAD

**Issue by omerlh** [OWASP/Top10#394]
How does the process of translation works? How should I start?

**Comment by sslHello** [comment]
Hi @omerlh - nice to hear from you. You were really fast!
We might have to do some follow-up work the next days., e.g. Wiki,...
You could fork the github 'master' branch. Andrew could send you some practical recommendations.
We do plan to provide the PPTX also in DIN-A4, but I can't guarantee that the text fits.
I've created a slack channel 'top-10-translations' right now, where you can reach the Top 10 team.
Cheers Torsten

**Comment by sslHello** [comment]
Hi @omerlh - You can find the Top 10 template in A4 also at github, now:
https://github.com/OWASP/Top10/blob/master/2017/translations/OWASP%20Top%2010-2017_Template_DIN-A4.pptx
Cheers Torsten

**Comment by sslHello** [comment]
Issue had been solved by commit cb5f896
