### ISSUE TITLE
Broken link to pptx file in main README.md

### ISSUE THREAD

**Issue by patriknordlen** [OWASP/Top10#397]
The main README.md points to https://github.com/OWASP/Top10/blob/master/2017/OWASP%20Top%2010%202017%20GM%20(en).pptx which doesn't exist. The 2017 README.md points to https://github.com/OWASP/Top10/blob/master/2017/OWASP%20Top%2010-2017%20(en).pptx which does.

**Comment by Neil-Smithline** [comment]
Thanks @patriknordlen!
