### ISSUE TITLE
A3: Should make "Incorrect Cryptography Usage" separate from "Sensitive Data Exposure"

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#40]
- I think the Top 10 should split the "Sensitive Data Exposure" into two categories : "Sensitive Data Exposure" and "Incorrect Cryptography Usage". The problem with cryptography is not just with whether you are using the right or wrong algorithm (primitive), it's also about how you assemble the whole thing. "Sensitive Data Exposure" focuses only on whether the primitive you are using are good (ex.: don't use RC4, MD5, etc.). From experience a lot of the issues with cryptography that I see come from the misassembling of the cryptography primitive. They pick "AES" ... but with the default mode ECB. They pick "AES/CBC" ... but they forget to use HMAC too (that almost always leads to padding oracle). They use "AES/CBC + HMAC" ... but they MAC before they encrypt. They pick "AES/GCM" or "AES/CBC + HMAC" ... but they individually encrypt different parameters (this leads to parameters swapping attack). They pick "SHA256" ... for password storage. Cryptography is a very hard field that has many caveats and every subtle mistake can potentially break the whole thing. This is, in my opinion, a lot more deserving than A7 and A10.

8.	Olivier Arteau

**Comment by jmanico** [comment]
+100 - Very astute comments.

--
Jim Manico
@Manicode

**Comment by davewichers** [comment]
Disagree this risk should be split. Do agree that this issue should be
clarified to cover all the issues Olivier has described.

**Comment by jmanico** [comment]
I'm more concerned with the depth of the feedback vs. the split as well.

--
Jim Manico
@Manicode

**Comment by Neil-Smithline** [comment]
FYI @HoLyVieR

**Comment by sslHello** [comment]
@HoLyVieR
Hi Olivier,
many thanks for your constructive comment.
I am sorry, we will need the space for 2 new forward looking issues. So we can't divide A6.
Thank you for your comments about "Incorrect Cryptography Usage", I've tried to add it at a glance:  
"* Encrypt all data in transit on application layer at least if any sensitive data may be transferred, e.g using TLS. Enforce this using directives like HTTP Strict Transport Security (HSTS).
* Ensure strong standard algorithms or ciphers, parameters, protocols and keys are used, and proper key management is in place."

Cheers
Torsten

**Comment by drwetter** [comment]
> "* Encrypt all data in transit on application layer at least if any sensitive data may be transferred, 

I would also add a remark for the backend. The worst thing which can happen is to do SSL offloading before the web server frontend with a crappy non-patched LB and then have one DMZ with ~100 of nodes, some patched, some in a bad condition. 

Suggestion:

"Encrypt all data in transit on application layer using TLS, at least if any sensitive data is being transferred through the internet - but mind also the backends in LAN/DMZ. For browsers enforce this using HTTP Strict Transport Security (HSTS)."

**Comment by jmanico** [comment]
+100 What a great idea, Dr. W.

--
Jim Manico
@Manicode

**Comment by sslHello** [comment]
@drwetter 
Hi Dirk,
thank you for your valuable suggestion. 
At the moment we are working to economize some space at the top table of A1 - A10. I'd like to come back to your suggestion when I know if we have space available after this changes. At the moment I am not sure if the content of 'How do I Prevent This?' and 'Am I Vulnerable to Data Exposue?' fits into the boxes of A6....
So I let this issue open until I know if any space is available.
Cheers Torsten

**Comment by vanderaj** [comment]
I've gone through and implemented as many of the feedback as possible. If there are any follow up comments, please use the QA finding #111
