### ISSUE TITLE
Wrong URL for DAST - Page 16

### ISSUE THREAD

**Issue by MacJu** [OWASP/Top10#402]
Page 16 the link of DAST leads to ZAP.
“Penetration testing and scans by **DAST** tools (such as OWASP ZAP) do not trigger alerts.”

Shouldn't it be : https://www.techopedia.com/definition/30958/dynamic-application-security-testing-dast

Mac

**Comment by wangjie8578** [comment]
Well notice :)

**Comment by gsilvapt** [comment]
I believe this issue no longer applies. Perhaps would make sense to close it?
