### ISSUE TITLE
German translation for Top 10 2017

### ISSUE THREAD

**Issue by p-w** [OWASP/Top10#407]
Servus,

creating a tracking ticket to announce the German translation efforts.
Feel free to join the translation team by leaving a comment here.

-pw

**Comment by sslHello** [comment]
Hello Peter,
thank you for opening this issue. There is already a German translating team, we meet at owasp.slack.com. Please send me a personal message to join us.
Cheers Torsten

**Comment by mum-viadee** [comment]
Hi Peter,

what is the current state of the german translation? Will the translation be published soon? Is there a schedule?

Greetings Martin

**Comment by sslHello** [comment]
Hi Martin,
the German translating team is working right now. But Peter has never joined us...
Well, we are all volunteers, but we plan to get it by the end of this year :-)
Cheers Torsten

**Comment by mrtnrdl** [comment]
Hi folks, I'm dropping in to offer my help. Are you @sslHello as well in the owasp slack?

**Comment by sslHello** [comment]
### German Version of the OWASP Top 10 - 2017 is released

We, a team of 14 OWASP volunteers, are pleased to inform you that we have released a German version of the OWASP Top 10 - 2017 at the German OWASP Day yesterday. 

The German OWASP Top 10 Team:
* Christian Dresen
* Alexios Fakos
* Louisa Frick
* Torsten Gigler
* Tobias Glemser
* Dr. Frank Gut
* Dr. Ingo Hanke
* Dr. Thomas Herzog
* Dr. Markus Koegel
* Sebastian Klipper
* Jens Liebau
* Ralf Reinhardt
* Martin Riedel
* Michael Schaefer

Commits: 8775428 (and d91ec0d, b3f8687, 3119ba3)

**Comment by sslHello** [comment]
Issue is closed
