### ISSUE TITLE
.pdf.pdf

### ISSUE THREAD

**Issue by doomguy** [OWASP/Top10#417]
Does anyone care to remove the extra .pdf from the current Top10 PDF?:

https://www.owasp.org/images/7/72/OWASP_Top_10-2017_%28en%29.pdf.pdf
to
https://www.owasp.org/images/7/72/OWASP_Top_10-2017_%28en%29.pdf

Regards

**Comment by gsilvapt** [comment]
I believe this issue no longer applies. Could you mention the section header so we can chase it around? GitHub's search feature doesn't reveal anything similar, except in the Japanese translation.

**Comment by szh** [comment]
The only place I can find this is here:
https://github.com/OWASP/Top10/blob/master/2017/ja/OWASP-Top-10-2017-ja.html#L1060

But that is the correct URL - the link would break if it was removed.

**Comment by doomguy** [comment]
Can't reproduce anymore.
