### ISSUE TITLE
OWASP Top Ten URL Schema

### ISSUE THREAD

**Issue by ziyahan** [OWASP/Top10#423]
Hi all,

For OWASP 2013 , there is URL schema:

https://www.owasp.org/index.php/Top_10_2013-{0}

the {0} param here is used to signify which item we want to show its details:

https://www.owasp.org/index.php/Top_10_2013-A1

When we open the link above, Wiki redirects us to:

https://www.owasp.org/index.php/Top_10_2013-A1-Injection

In past, no need to put "Injection" or order explanation of the top 10 in URL.

But now, in wiki page of OWASP2017, we cannot use an URL like below:

https://www.owasp.org/index.php/Top_10-2017_A1

it does not redirect us to below:

https://www.owasp.org/index.php/Top_10-2017_A1-Injection

Could you add support for this please again. It would be great, otherwise we will have to map it manually.

Thanks in advance.

**Comment by Neil-Smithline** [comment]
Fixed by @ziyahan. Thanks!
