### ISSUE TITLE
+F, +T: Move Appendix F & T to the front

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#43]
2) At the end of the document the project leaders actually make it fairly clear that the Top 10 is a list of risks and not vulnerabilities, and they even give a link to the specific methodology that is used to determine those risks. I’m glad they make that clarification, although I think it should be done at the very top of the document rather than at the end. ]

**Comment by sslHello** [comment]
+T: Add reference to #23

**Comment by vanderaj** [comment]
I'm going to move +R and +F to the front, because they provide context to what follows, but I'm not going to move +T, as that's a "what next" element
