### ISSUE TITLE
Russian translation for TOP 10 2017

### ISSUE THREAD

**Issue by hamster4n** [OWASP/Top10#437]
Hello,

We are starting Russian translations. Please, feel free to join.
https://github.com/hamster4n/Top10

Cheers.

**Comment by JZDLin** [comment]
Hello,
Actually, it has already been started here (https://github.com/PositiveTechnologies/Top10/tree/master/2017/ru)

**Comment by JZDLin** [comment]
Join us at https://github.com/PositiveTechnologies/Top10/tree/ru-translation
The **ru-translation** branch contains the most up-to-date translations

**Comment by oxdef** [comment]
@JZDLin BTW, what is current status? Do you need any help?

**Comment by JZDLin** [comment]
Hi @oxdef,
It's now fully translated. There's a pull request waiting for merge.
Wanna make some kind of a review?

**Comment by oxdef** [comment]
> Wanna make some kind of a review?
Yes, let's try.

**Comment by sslHello** [comment]
Hi @JZDLin, 
Congratulations for your translation efforts.
I am sorry to say,  there are some issues with commit request #458 (details see there):
Could you please send a new request.
Thank you so much.

Cheers
Torsten

**Comment by sslHello** [comment]
Thanks, the merge worked now.

**Comment by sslHello** [comment]
See commit 4f261e7

**Comment by sslHello** [comment]
Do you have access to owasp.org?
If not, please let me know whal you are ready and I'll copy it to the translations page: https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project#tab=Translation_Efforts_2
Cheers
Torsten

**Comment by oxdef** [comment]
@sslHello @JZDLin  Please, give me some time to finish review of PR

> Do you have access to owasp.org?

BTW, I have access.

**Comment by JZDLin** [comment]
> @sslHello @JZDLin Please, give me some time (1-2 days) to finish review of the PR

@oxdef @sslHello Yes, it's a good idea to finish the review before publishing the final version, just to confirm that everything is in its place and sounds reasonable.

BTW, I do not have access.

**Comment by oxdef** [comment]
Happy New Year!

Just have finished the review. Please, read my comments in https://github.com/OWASP/Top10/pull/458

**Comment by KvanTTT** [comment]
@sslHello I guess this issue should be closed for now.

**Comment by sslHello** [comment]
@KvanTTT Hi Ivan, should we let it open until the Russian version is going to be finalized?

**Comment by KvanTTT** [comment]
Ok, let leave it open.

**Comment by sslHello** [comment]
Congratulations for publishing the Russian Version of the OWASP Top 10:2017.
Pull Request #460, Commit e6d3773
Cheers Torsten

**Comment by oxdef** [comment]
Added PDF version to https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project#tab=Translation_Efforts_2
