### ISSUE TITLE
French translation : 0x02 foreword

### ISSUE THREAD

**Issue by inaz0** [OWASP/Top10#453]
**Petites coquilles dans la traduction et pinaillage  :** 

> Un grand nombre de remarques ont été reçues au cours de la création de l'OWASP Top 10 - 2017, plus que lors de n'importe autre travail de l'OWASP. Cela montre à quel point la communauté entretient une réelle passion pour l'OWASP **Top 10. et donc** à quel point il est essentiel pour l'OWASP d'avoir raison dans la majorité des cas d'utilisation. 

=> Soit ajouter une virgule soit une majuscule pour le **. et**

> Nous avons écrit un éventail de potentielles prochaines étapes pour différents types d'utilisateurs de l'OWASP Top 10, incluant notamment "Que faire ensuite pour les Développeurs", "Que faire ensuite pour les Testeurs en Sécurité", "Que faire ensuite pour les Organisations", qui est tout à fait approprié pour les **DSIs et les RSSIs**, et "Que faire ensuite pour les Managers d'Applications", qui est approprié pour les managers d'applications mais également pour toute personne responsable d'une application durant son cycle de vie .  

=> ne pas avoir de S  à la fin de DSI et RSSI

> Sur le long terme, nous encourageons toutes les équipes de développement logiciel et les organisations **a créer un** 

=> **à créer un**

**Comment by SPoint42** [comment]
assign to @SPoint42

**Comment by SPoint42** [comment]
close

**Comment by sslHello** [comment]
@SPoint42: should I close this issue?

**Comment by SPoint42** [comment]
Yes
