### ISSUE TITLE
French -Translation 

### ISSUE THREAD

**Issue by SPoint42** [OWASP/Top10#454]
Hi @sslHello ,
could you please create a Label for the French translation ? 
It will be better to track the review requested by Frenchs guys

Thanks .

**Comment by sslHello** [comment]
Salut Sebastien,
I've created a speciacl label for the French translation. Please verify that it works four you.
Salutations / cheers
Torsten

**Comment by sslHello** [comment]
BTW it is in french blue / Bleu de France ;-)
