### ISSUE TITLE
French translation : remarques sur divers fichiers

### ISSUE THREAD

**Issue by FyndhornElder** [OWASP/Top10#455]
0x00-notice.md :
$ 6 : mettre un accent sur le 'a' "Appel **à** commentaires".
§ 7 : ajouter un 'e' à 'util'. A la fin de cette ligne, plutôt que "qui est en version PowerPoint/PDF." je mettrais "qui est la version PowerPoint/PDF."

0x01-about-owasp.md :
§ 5, plutôt que "L'Open Web Application Security Project (OWASP)" je mettrais "OWASP (_Open Web Application Security Project_)". Avec éventuellement un L' devant OWASP.

0x06-release-notes.md:
§ 11 : "JavaScript est aujourd'hui le premier langage web avec node.js côté Serveur et**,** de nouveaux environnements " Supprimer la virgule après et.
§ 21 : A8:2017-Désérialisation non Sécurisée. Dans 0x05-introduction.md ligne 5, le titre employé était "Désérialisation sans validation". Une homogénéisation est nécessaire.

0xa2-broken-authentication.md :
§ 6 : Ajouter un 's' à mot et remplacer "brute force" par "force brute" dans : "| Les attaquants ont des accès à des centaines de millions de combinaisons de logins et **mot** de passe, des comptes par défaut d’administration, d’outils de **brute force** automatisés, "

0xa4-xxe.md
§ 6 : Ajouter un 'a' à "attquant" (première ligne).
Ligne 5 : accorder les genres en ajoutant des 'e' dans "une URI déréférencé**e** et évalué**e** lors du traitement XML. ".
Ligne 8 : mettre le verbe au pluriel "Les outils DAST nécessite**nt** ".
Ligne 10 : accorder "testeurs doivent être formés à la façon manuel**le** de tester les XXE, car il**s** n'étai**en**t pas couramment testé**s** en 2017.".

0xa5-broken-access-control.md :
§ 6 : ligne 3, remplacer 'and' par 'et' dans "(https://www.owasp.org/index.php/Source_Code_Analysis_Tools) **and** [DAST]".

**Comment by SPoint42** [comment]
close

**Comment by sslHello** [comment]
@SPoint42: should I close this issue?

**Comment by SPoint42** [comment]
Yes
