### ISSUE TITLE
A10 Feedback

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#46]
4) "A10 - Underprotected APIs" is obviously covered by the other 9 items, but it's not a bad idea to raise awareness on them. I still see lots of developers who think that HTML forms are the only attack surface of a web application. So like XSS and CSRF are injection attacks, it's not a bad idea to focus on them for a while. Maybe we should change A10 to SSRF in 2020? Keeping the last one for awareness isn't a bad idea...
Overall, I'm quite pleased with the new Top 10 as I feel they better reflect what I've been seeing in my assessments. 2017 is definitively better than the 2013 version, so good job!! ;)
11.	David Caissy

**Comment by Neil-Smithline** [comment]
Based on the results of the industry survey ([background on survey](https://owasp.blogspot.com/2017/08/owasp-top-10-2017-project-update.html)), API vulnerabilities will not be in the Top-10. Where appropriate, mentions of API vulnerabilities will be added to other risks.
