### ISSUE TITLE
Portuguese Translation for TOP 10 2017

### ISSUE THREAD

**Issue by PauloASilva** [OWASP/Top10#463]
Hi guys,
The Portuguese (pt-pt) translation is complete and I would like to open the Pull Request but I am not sure to what branch it should be done (`master` or `golden-master`)?

The `README.TRANSLATIONS` is not clear about that

> When you're ready for us to consume your translation, please create a pull request, and we'll merge your changes.

Can you please provide some guidance?

Cheers,
Paulo A. Silva

**Comment by Neil-Smithline** [comment]
`master`

**Comment by PauloASilva** [comment]
Hey @Neil-Smithline,
Thanks for you help.

Please review PR #464.

Cheers,
Paulo A. Silva

**Comment by Mockingbot94** [comment]
good job

**Comment by sslHello** [comment]
Congratulations for the Portuguese Version of the OWASP Top 10!
Thank you for your great volunteerism!
Merged with commit 59cc94a.

Cheers
Torsten

**Comment by sslHello** [comment]
Do you like to add it yourself at [the Project Page](https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project#tab=Translation_Efforts_2)?
Please let me know if I should do it for you and who should be attributed.
Cheers Torsten

**Comment by PauloASilva** [comment]
Hi @sslHello,
Thanks for your help merging the Portuguese version.

I will add it myself to the Project Page in a few minutes.

Cheers,
Paulo A. Silva

**Comment by PauloASilva** [comment]
Hi @sslHello,
I had no timely response to my account request.
Because of that I would like to ask you to add the Portuguese translation to the Project Page.

You should first accept the [PR #465][1] as it moves the PDF and ODP files to the Top 10 2017 root directory (`/2017`). Then, please add the following line right after the Korean one

```
* Portuguese <u>[https://github.com/OWASP/Top10/tree/master/2017/OWASP%20Top%2010-2017-pt_pt.pdf OWASP Top 10 2017 - Portuguese (PDF)]</u>&nbsp;<u>[https://github.com/OWASP/Top10/tree/master/2017/OWASP%20Top%2010-2017-pt_pt.odp (ODP)]</u><br/> translated by Anabela Nogueira, Carlos Serrão, Guillaume Lopes, João Pinto, João Samouco, Kembolle A. Oliveira, Paulo A. Silva, Ricardo Mourato, Rui Silva, Sérgio Domingues, Tiago Reis, Vítor Magano.
```

Cheers,
Paulo A. Silva

[1]: https://github.com/OWASP/Top10/pull/465

**Comment by sslHello** [comment]
Moved with committ e529e4e

**Comment by PauloASilva** [comment]
Great!
Please find below the line to add to the Project Page: I've had no answer to my account request.

```
* Portuguese <u>[https://github.com/OWASP/Top10/tree/master/2017/OWASP%20Top%2010-2017-pt_pt.pdf OWASP Top 10 2017 - Portuguese (PDF)]</u>&nbsp;<u>[https://github.com/OWASP/Top10/tree/master/2017/OWASP%20Top%2010-2017-pt_pt.odp (ODP)]</u><br/> translated by Anabela Nogueira, Carlos Serrão, Guillaume Lopes, João Pinto, João Samouco, Kembolle A. Oliveira, Paulo A. Silva, Ricardo Mourato, Rui Silva, Sérgio Domingues, Tiago Reis, Vítor Magano.
```

Cheers,
Paulo A. Silva

**Comment by sslHello** [comment]
Hi Paulo,
thank you. Your Portugese version is now onlile via the OWASP web site: [OWASP_Top_Ten_Project](https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project#tab=Translation_Efforts_2).
I've copied the pdf directly to the Wiki. The ODP is too big, it links diretly to the RAW github path of the file. 
I am sorry about the delay of your account request. I'm sorry, I'm only a volunteer myself and not involved to this. 

Cheers,
Torsten

**Comment by PauloASilva** [comment]
Hi @sslHello,
This is awesome!

Thanks for you help.

Cheers,
Paulo A. Silva
