### ISSUE TITLE
A7, Risk: On "Risks" 

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#47]
... my suggestion would be to add the qualifier in addition to the examples. "Certainly of course this does not mean hacking back" etc. There is no way at some point someone doesn't get hung up on that..

For Risk, the reference to Microsoft Threat Modeling Tool seems out of place since that's not the approach the T10 diagrams take. The FAIR stuff is little left field. Is a little jarring/top of mind since rolling out Microsoft TMT at VA is all. Limited tool choices of course and spotty OWASP info on the topic. Maybe consider a standalone threat modeling page with 1 cohesive suggestion/view. T10 is getting pretty big though at this point especially as it pivots to devops etc.

12.	Mike Boberski:

**Comment by sslHello** [comment]
RISK: Add reference to #13

**Comment by Neil-Smithline** [comment]
FYI: @Boberski

**Comment by vanderaj** [comment]
This risk is going to be removed as per community feedback at the Project Summit, survey data and revised data call. Thank you for your input on this matter.
