### ISSUE TITLE
Design data collection

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#480]
@infosecdad Please attach your plan (OWASP Top 10 2020 Data Analysis Plan.docx ) to this ticket. 
@sslHello Please attach your work to this ticket. 

Let's use the Wiki to document our data collection design, process, and analysis.

**Comment by vanderaj** [comment]
Draft in Google drive 
@sslHello to link the document for read only public consumption

**Comment by secureideas** [comment]
May I ask where this Google drive is so we can help?

**Comment by infosecdad** [comment]
Here is a draft Data Analysis Plan that we have been working on.[https://github.com/OWASP/Top10/blob/master/2020/Data/OWASP%20Top%2010%202020%20Data%20Analysis%20Plan.docx](url)

**Comment by vanderaj** [comment]
Data collection is complete.
