### ISSUE TITLE
Call for data scientists

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#487]
Working with @infosecdad as lead, call for community data scientists to assist in the collation and analysis of data.

**Comment by cgivre** [comment]
Hello @infosecdad 
I'd be interested in participating/contributing.  What is the process?
Thanks

**Comment by carolynduby** [comment]
Hi @infosecdad 
I would also be interested in helping.   

Thanks
Carolyn

**Comment by infosecdad** [comment]
Excellent, thank you two. I'll be in touch.

**Comment by xufuou** [comment]
Hi @infosecdad, in case there is still need I would also like to contribute.

Thanks.

**Comment by infosecdad** [comment]
All, here is a draft of the data collection and analysis plan that we are looking at, please let me know what you think. 
[OWASP Top 10 2020 Data Analysis Plan.docx](https://github.com/OWASP/Top10/files/4250682/OWASP.Top.10.2020.Data.Analysis.Plan.docx)

We probably need to setup a Slack channel on the OWASP Slack or something similar to help facilitate communications.

**Comment by vanderaj** [comment]
Data collection is complete.
