### ISSUE TITLE
Should mentions of "TLS" be changed to "TLS 1.1/1.2"

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#49]
* Page 13 - A6 - Sensitive Data Exposure - Example Attack Scenarios - says "Scenario #2: A site simply doesn’t use TLS for all authenticated pages." which, in my opinion, should be written as "Scenario #2: A site simply doesn’t use TLS 1.1/1.2 for all authenticated pages." – No change. The point is that they aren’t using TLS (or SSL) at all. Not specific versions of TLS.

13.	Graeme Wicksted

**Comment by Neil-Smithline** [comment]
I  believe that we should make this change for all references or none.

**Comment by Neil-Smithline** [comment]
@gwiksted - CCing you on this issue. Please let me know if you're the wrong user.

**Comment by bchurchill** [comment]
As time goes on there's no guarantee that TLS 1.1/1.2 will be the best recommendation.  Sometimes these protocols are broken (as was SSL 3 and TLS 1.0, for example).  As of now, correct implementations of TLS 1.1 and TLS 1.2 are considered secure, but we have no guarantee they won't be broken before the next OWASP Top Ten release.  Already TLS 1.3 is in working draft and it's possible that it would be desired in the future.  I'm not sure what the best way to communicate this is in the Top Ten document.  Maybe we can describe a particular TLS implementation as "up-to-date" or "fully patched" to not only capture that the correct protocol is being used, but that the implementation isn't faulty as well; but I'm not sure how that would fit into the particular sentence we're discussing.

**Comment by sslHello** [comment]
@bchurchill - Thank you for your comment.
Yes we will definitely update A6, even TLS1.2 has had some introduced issues...
And yes we are waiting for TLS 1.3. Yes, it is a question of patching and using the up-to-date ciphers and parameters. I'd also suggest to avoid to mention Version numbers (perhaps besides negative examples).
Please take also a look at #71.

Cheers Torsten
OWASP Top-10 Co-Leader

**Comment by jmanico** [comment]
I suggest make the rule generic and time-friendly. "Use the most accepted, secure and relevant version of TLS that is available" or similar.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by sslHello** [comment]
I've just extended 'How do I prevent' to
"* Ensure _up-to-date and_ strong standard algorithms or ciphers, parameters, protocols and keys are used, and proper key management is in place. Consider using FIPS 140 validated cryptographic modules."
I hope this solves your finding (besides referencing version numbers as discussed above). Issue resolved. Please review updated text.

**General note:** The 'How do I prevent' uses a lot of space. We are working to get more space for this section. I am sorry, but the overall text may need to be shortened at the end, if the obtained additional space is too small...
