### ISSUE TITLE
time out.

### ISSUE THREAD

**Issue by GraoMelo** [OWASP/Top10#497]
https://github.com/OWASP/Top10/edit/master/2017/de/readme.md

line 4: The official website is here: https://www.owasp.org/index.php/Germany/Projekte/Top_10

retorn Error 404

**Comment by catchingknives** [comment]
Works for me. The link in the file and the link you posted above are identical

**Comment by GraoMelo** [comment]
ok. on my machine it works is a great excuse. do as you wish the warning has already been given.
