### ISSUE TITLE
OWASP Top 10 - 2021 - Proposed A5

### ISSUE THREAD

**Issue by jmanico** [OWASP/Top10#515]
Hello T10 team.

The current proposal for the next OT10 proposes mixing Insecure Deserialization and XXE. From a defense POV this seems unnatural.

Deserialization defense requires the use of specialized input filtering of serialization data like [JEP 290](http://openjdk.java.net/jeps/290), as well as very specific class design in the java world. While XXE required configuration of a XML parser.

I would prefer that we pick one as opposed to merging these very different items.

Respectfully, Jim
cc @vanderaj

**Comment by mkonda** [comment]
I agree that the defense is different but when I present these to teams, they feel redundant.

I would prefer a single Top 10 item for deserialization with XXE as a specific case of it, like SQLi is a specific case of Injection.

**Comment by jmanico** [comment]
> I would prefer a single Top 10 item for deserialization with XXE as a specific case of it, like SQLi is a specific case of Injection. Of course, by this logic, XSS should perhaps also be Injection.

XXE has nothing to do with deserialization. XXE occurs because of features in an XML parser that should be disabled. Deserialization is about sending binary serialized data into deserialization endpoints with no object filtering. They are not related.

**Comment by mkonda** [comment]
> > I would prefer a single Top 10 item for deserialization with XXE as a specific case of it, like SQLi is a specific case of Injection. Of course, by this logic, XSS should perhaps also be Injection.
> 
> XXE has nothing to do with deserialization. XXE occurs because of features in an XML parser that should be disabled. Deserialization is about sending binary serialized data into deserialization endpoints with no object filtering. They are not related.

But the feature that is being disabled *is* object filtering.  ;)

**Comment by jmanico** [comment]
> But the feature that is being disabled is object filtering. ;)

It's significantly different. You're comparing the complexity of JEP-290 with XML configuration.  I can flip a few switched on an XML parser and I'm safe.

Deserialization on the other hand is inherently unsafe and merging the two is unnatural from a defense POV.,Deserialization defense is actually way more complex. It should just be avoided, but if you really need that feature look at all the guidance around object design and similar https://www.oracle.com/java/technologies/javase/seccodeguide.html

Defense between the two categories is radically different the deeper you look.

**Comment by mkonda** [comment]
> > But the feature that is being disabled is object filtering. ;)
> 
> It's significantly different. You're comparing the complexity of JEP-290 with XML configuration. I can flip a few switches on an XML parser and I'm safe.
> 
> Deserialization on the other hand is inherently unsafe and merging the two is unnatural from a defense POV. Deserialization defense is actually way more complex than just object filtering. It should just be avoided, but if you really need that feature look at all the guidance around object design and similar https://www.oracle.com/java/technologies/javase/seccodeguide.html
> 
> Defense between the two categories is radically different the deeper you look.

I'm not sure it is as different as you are saying.  

For either one, my first recommendation would be try to avoid doing it at all (eg. turn of parsing and make sure you don't have any readObject).  My second warning would be that there may be infrastructure code that you need to think about (framework code magic that parses or deserializes).  My third recommendation would be if you do need to support it, you need to worry about a LOT of details.

What if you want to support some external entities but not all?  That starts to feel a lot like the same problems you see dealing with Java deserialization.

Also, should JSON serialization be considered more like XML or Java deserialization?  I would argue it kind of sits in the middle with attributes of both.

Anyway - I'm not trying to pick a fight here.  It is possible we are both correct for different reasons and we should hear more people's input.

**Comment by jmanico** [comment]
From @infosecdad one of the project leads:

"currently have no intention of merging those two as I don’t see them being related enough to do so"

The "proposed" OWASP Top Ten 2021 was vendor shenanigans and not an official OWASP release. I am closing this out.

**Comment by jmanico** [comment]
> What if you want to support some external entities but not all?  That starts to feel a lot like the same problems you see dealing with Java deserialization.

I disagree. Supporting external entities involve an allow-list of valid URL's or similar, it's quite simple. Building secure deserialization functionality is massively complex and involves careful object design (like the use of transient in some placed), as well as filtering of incoming serialization data and more which is wickedly more complicated that XXE. This is why XXE has been largely fixed at the language level (like .NET 4.5.2+ XXE is universally addressed and deserialization defense is not (and can not) be fixed at the language level universally like XXE is. You can build a helper class like Python's difusedxml that makes XXE completely go away, you can not do the same for deserialization issues.

> Also, should JSON serialization be considered more like XML or Java deserialization? I would argue it kind of sits in the middle with attributes of both.

Most JSON problems are fixed by A9, updating your library. 

> Anyway - I'm not trying to pick a fight here.

Well I am! Bring it on! To quote Captain America "I could do this all day." What else do you got? I'm not going to give up. :)
