### ISSUE TITLE
A5: Reference suggestions

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#53]
I've reviewed all the references under "A5 - Security Misconfiguration" and my suggestion is to replace "OWASP Top 10 2004 - Insecure Configuration Management" with "OWASP Secure Headers Project" since is a high level recommendation and also covered by the other references above. The last modified footer is also saying "October 2008" which is a little bit older.

17.	Ricardo Iramar dos Santos

**Comment by vanderaj** [comment]
Talking about the example in the other three boxes it's a difficult to say so I'll go by exclusion. I wouldn't changed anything on "Am I Vulnerable to Attack?" or "How Do I Prevent This?" because IMO they are pretty solid and aligned with A5. And the item 5 under "Am I Vulnerable to Attack?" is already covering the security headers settings indirectly. So it needs to be some item from "Example Attack Scenarios". 
The Scenario #4 under "Example Attack Scenarios" could be replaced since is talking about something that it's enabled by default and it should be removed. If you see Scenario #1 is about almost the same thing the only difference is instead of sample application is about admin console.
As you may have noticed I'm not a native English speaker so I'll put my suggestion for the possible new Scenario #4 below but most probably the English needs to be reviewed and updated.
Scenario #4 The app server do not send HSTS response header back to the user browser allowing a victim open connection in clear text (HTTP). A nearby attacker can possibly eavesdrop the connection stealing sensitive data or perform a MITM attack.

**Comment by riramar** [comment]
Just to avoid confusions this suggestion make sense to be implemented only if the changes from #80 will be also implemented.
The #53 and #80 were part of the same comments that I sent to Dave. I can share the original e-mail if you guys want.

**Comment by sslHello** [comment]
Hi Ricardo,

I have added to 'Am I vulnerable to attack?'
  6. Does the server not send any security directives to client agents (e.g. in headers) or are they not set to secure values?'
and I've made a note of 'OWASP Secure Headers Project' at References 
Issue resolved by the update mentioned above. Please review the updated text.

**Comment by riramar** [comment]
Checked and the text is ok. Thanks @sslHello !
