### ISSUE TITLE
Top10 Sitrep 

### ISSUE THREAD

**Issue by yosignals** [OWASP/Top10#532]
Hey guys, I had a little rant here last night https://twitter.com/YoSignals/status/1435734599410278405?s=20 but it's worth expanding 

The scope and audience of  top ten I’d expect it to be  something like this:
Issue > effect > technical defence > policy control (x10)

What we've seen over the years is the document blurring into something that's just a title with broad statements about architecture 

that might be around the limited data that's available to conclude insight, or it might be that people that used to focus on XSS,XXE,SQLI,RFI realise that it's generally 'bad code & bad architecture'  I don't like the dilution from (broadly) a list of specific attack types to now a set of security architecture principles (aside from [SSRF] and Merge ["Insecure Deserialization" into "Injection"](https://github.com/OWASP/Top10/issues/530) , So i guess, what I'm saying is if you're going to boil things down to higher levels, I'd argue that fewer people need to read it, and it becomes less useful 

![](https://owasp.org/Top10/assets/image1.png)
I remember last year or the year before having a conversation about a previous top10 having blurred the lines between cause and effect, I think i can say that hasn't gone away yet  (i was using @n0x00 account then) 

So, 

Broken Access Control is it a cause or an effect? I'd say effect, because if you were doing root cause analysis there would be an underlying technical failure as to why the Access Controll is broken

Similarly, Cryptographic Failures, Injection, Insecure Design, Security Misconfiguration, outdated components, Ident and auth failures, Data integrity, logging and monitoring but not SSRF

I think I may well be missing the point of the document?

I'd be happy to get involved if it followed a logical path such as

Issue > effect > technical defence > policy control (x10) 

I feel like we have mostly a list of effects, but not the _actual_ top10 issues that drive them 

and I don't want anyone to feel bummed out by my criticisms, i know it's a community effort and if any of you are in south London I'll buy you a coffee and we can put the world to rights

**Comment by yosignals** [comment]
<img width="1238" alt="Screenshot 2021-09-09 at 23 55 45" src="https://user-images.githubusercontent.com/72615869/132865135-a419be4e-9688-4556-9664-1842d4755bf2.png">
the logical flow of the current 2021 list feels a bit like this to me

**Comment by vanderaj** [comment]
We really appreciate your feedback. We will try to tweak the insecure design to make it clearer.

I'm sorry, it's a bit too late for such a huge level of feedback.
