### ISSUE TITLE
Position of Injection Vilnerabilities

### ISSUE THREAD

**Issue by craigfrancis** [OWASP/Top10#535]
I agree “Broken Access Control” needs to move up the list, and fine with it being 1st.

But, compared to “Cryptographic Failures”, while that can be fun to talk about, I’d still argue that “Injection” issues are more of an issue.

Especially as Injection now (correctly) includes XSS, this makes this category incredibly common; with SQLi being incredibly damaging (and still common, just watch the typical answers given on a popular tech support website).

**Comment by vanderaj** [comment]
We have a lot of data that supports the order that we have. I'd suggest that you register for Brian's talk tomorrow to learn about how we collected, analysed and built the OWASP Top 10. 

https://owasp20thanniversaryevent20.sched.com/event/myc2/owasp-top-10-flagship-project-the-making-of-the-owasp-top-10-and-beyond
