### ISSUE TITLE
A:08 - 2021 - Lack of Accountability

### ISSUE THREAD

**Issue by lcaoppit** [OWASP/Top10#536]
Hi team,

In A:08 - 2021 - Security Logging and Monitoring Failures, we saw that "failures in this category can directly impact visibility, incident alerting, and forensics". We could tell that it impact on lack of accountability, because whithout logging I can't check who did the action, right?

Very well work!!!!

**Comment by jmanico** [comment]
> We could tell that it impact on lack of accountability, because 
whithout logging I can't check who did the action, right?

Logging is not the right sole place for accountability. I typically use 
a careful database to track user actions when I need real 
accountability. I can tie data together better in a RBDMS or similar. A 
database is also way more integrated with my app than a log system, and 
I often want accountability-visibility in my admin side of the app 
itself, and for that I want a well designed database.

**Comment by lcaoppit** [comment]
Thanks to anwser me @jmanico . I understood your approach very well.

There are some environmet that do not apply this kind of practice and unfortunately rely more on the syslog server or simply do not treat your logs and app error. 

Then I though that A:08 can be told about accountability as weel.

Thanks again.

**Comment by infosecdad** [comment]
"accountability" will be added to the verbiage, thank you!
