### ISSUE TITLE
Update references

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#54]
QA (we must hear from a majority of project leads saying approved before closing)

- [x] Ready for review?
- [ ] Spelling
- [ ] Content
- [ ] Issues are modern, deal with apps and API?
- [ ] Recommendations are modern, deal with apps and API?
- [ ] Example scenarios, reference real world breaches? 
- [ ] Can it be any smaller without losing information?
- [ ] Links (if any) - OWASP primary sources, stable secondary sources?

BTW the external reference "CIS Security Configuration Guides/Benchmarks" (http://benchmarks.cisecurity.org/downloads/benchmarks/) is broken. Maybe this should be pointed to https://www.cisecurity.org/cis-benchmarks/.
17.	Ricardo Iramar dos Santos

**Comment by sslHello** [comment]
+1 and all references should be https if available. The latter has been already made in the RC1-Wiki of the Top 10-2017
Cheers Torsten

**Comment by riramar** [comment]
Do you guys know if all the other references were checked? If not I can do it.

**Comment by sslHello** [comment]
Hi Ricardo,
thank you very much for your nice offer. We will have to redo this definitely just before RC2 and the 'golden master'.
Do you check them manually or do you use a script for this?

**Comment by riramar** [comment]
Hi @sslHello I do manually.

**Comment by vanderaj** [comment]
When QA"ing, this applies to all risks and not just A5, so removing A5 from it.

**Comment by vanderaj** [comment]
Please review each and every reference. Each reference must be:

* Primary. It should be OWASP if at all possible as a primary source, or a well known book or paper by a noted researcher or organization 
* Maintained. If a project hasn't put out a release in the last two years, don't include it unless it's very special indeed.
* Stable. We publish for three years
* Relevant. Only include a link if it's directly relevant to the issue at hand.

**Comment by vdbaan** [comment]
Reference to Testing guide is missing (https://www.owasp.org/index.php/OWASP_Testing_Project)

**Comment by vanderaj** [comment]
I've reviewed the References section and it's ready for RC2 now (see #143). Individual chapter references still need verifying so I am leaving this issue open.

**Comment by vanderaj** [comment]
@vdbaan - fixed. Thanks - I've included all Flagship documentation projects, and all flagship tool projects, and a selection of references Lab projects, including the Developer Guide.

**Comment by vanderaj** [comment]
We have to fix or remove any residual http:// links. We can't ask for TLS everywhere and allow unencrypted content. The ZDNet article and a few of the version control links are left. Let's get rid of them or replace them with sites that do TLS.

**Comment by vanderaj** [comment]
The RC2 PPTX does not have any References section. We might revisit this later.
