### ISSUE TITLE
add full forms for abbreviations

### ISSUE THREAD

**Issue by shubhangi013** [OWASP/Top10#558]
There should be a separate section for the full forms (and maybe definitions) of the commonly used terms like CWE and DAST etc., or the full forms must be provided when they're first used in the list.
The second one seems more appropriate, in my view. This'll ensure an engaging reading experience for the readers.

**Comment by Neil-Smithline** [comment]
Thanks for the feedback

**Comment by shubhangi013** [comment]
You're welcome!
