### ISSUE TITLE
A2, A4, A7, A10: Enumerate 'bucket' categories

### ISSUE THREAD

**Issue by psiinon** [OWASP/Top10#56]
Some of the Top 10 categories are pretty well defined, such Injection, XSS, CSRF and Using Components with Known Vulnerabilities.
Others, like Broken Authentication and Session Management, Broken Access Control, Insufficient Access Control and Unprotected APIS are much broader and cover a multitude of sins.
If the Top 10 is to keep such 'bucket' categories then I think we should at least try to clearly enumerate the main vulnerabilities that the relevant category covers.

**Comment by vanderaj** [comment]
A7 and A10's are going to be removed as per community feedback at the Project Summit, survey data and revised data call. Thank you for your input on this matter.
