### ISSUE TITLE
Broken link for NIST document

### ISSUE THREAD

**Issue by chimmichurri** [OWASP/Top10#560]
NIST document under references in:https://owasp.org/Top10/A04_2021-Insecure_Design/
was broken

https://www.nist.gov/system/files/documents/2021/07/09/Developer%20Verification%20of%20Software.pdf

I looked for the correct link and it should be: 

https://www.nist.gov/system/files/documents/2021/07/13/Developer%20Verification%20of%20Software.pdf

**Comment by t-gv** [comment]
You could probably use the link from their post announcing that document : [https://www.nist.gov/document/document-developer-verification-software](https://www.nist.gov/document/document-developer-verification-software) which redirect to the good url.

**Comment by Neil-Smithline** [comment]
Thanks!
