### ISSUE TITLE
Clarify wording on A04 Insecure Design

### ISSUE THREAD

**Issue by chimmichurri** [OWASP/Top10#561]
The description states that, "Ineffective insecure design is where a threat could be realized, but insufficient domain (business) logic validation prevents the action."
<img width="1402" alt="Screen Shot 2021-09-13 at 5 06 48 PM" src="https://user-images.githubusercontent.com/90607752/133056762-6fcd0e8c-e22e-4ded-a343-5b671f1fd513.png">

The wording seems confusing especially after the "..prevents the action part"? Does that mean that having the ineffective insecure design prevents the attack from happening?

**Comment by sslHello** [comment]
Yes, I see. It seems that a part of the sentence(s) has been lost....

**Comment by infosecdad** [comment]
This has been fixed, thanks for opening the issue.
