### ISSUE TITLE
2021:A8 - Software and Data Integrity Failures

### ISSUE THREAD

**Issue by SeanWrightSec** [OWASP/Top10#571]
The SolarWinds example doesn't feel correct as an example in this category. The SolarWinds incident was a result of the attackers injecting their code within the build system. This would mean any data relating to the integrity of the final package would have included the payload. The end result being that any customer how verified the update package would have determined that the updated package was legitimate and could be trusted.

**Comment by jmanico** [comment]
I agree with Sean here. The CodeCov incident is more recent and much 
more relevant for this category.

https://about.codecov.io/security-update/

**Comment by SeanWrightSec** [comment]
The CodeCov is an excellent example!

**Comment by infosecdad** [comment]
Thanks for the feedback, we're updating it to make it clearer that both the integrity of the software package and the process to build it is in scope here. So SolarWinds is applicable, as is the CodeCov that @jmanico mentioned which we will add.
