### ISSUE TITLE
Missing "not" in "The ASVS is the only acceptable choice for tool vendors."

### ISSUE THREAD

**Issue by fdavis99** [OWASP/Top10#573]
OWASP Top 10:2021 (DRAFT FOR PEER REVIEW) > How to use the OWASP Top 10 as a standard
Last paragraph seems to be missing "not" 

"The ASVS is the only acceptable choice for tool vendors."

**Comment by sslHello** [comment]
I am sorry, I don't see the issue here. ASVS is the standard, the Top 10 the awareness and appetizer document ;-)

**Comment by vanderaj** [comment]
The ASVS is the standard. Won't fix.
