### ISSUE TITLE
A3 tweaks from Eelgheez

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#59]
This person edited A3 directly. There changes are described here:
https://www.owasp.org/index.php?title=Top_10_2017-A3-Cross-Site_Scripting_%28XSS%29&type=revision&diff=230186&oldid=229058
We reverted these changes on the wiki so it matches the Release Candidate, but wanted you to be aware of these suggested changes, which you might want to incorporate.

**Comment by sslHello** [comment]
Add reference to #31

**Comment by Neil-Smithline** [comment]
Many comments incorporated in change b712034.

**Comment by ilatypov** [comment]
The abuse includes not just creating a link with a malicious payload but also luring the victim to either open in or visit another vulnerable site that will have a redirect to the attacked site using the malicious payload.
