### ISSUE TITLE
Early release of just the Top 10 list (Summit Process session, Mon AM1)

### ISSUE THREAD

**Issue by tghosth** [OWASP/Top10#6]
Would it make sense to publish the proposed Top 10 list without writing the full document so as to gather feedback on the suggested Top 10 before embarking on the full document creation?

**Comment by jmanico** [comment]
+1 for open processes, open discussion, open document editing, open data call and open data analysis. 😎

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by tghosth** [comment]
So the purpose here was more practical so that someone doesn't spend ages writing a long document which then has to undergo significant changes of the Top 10 themselves are changed,

This was discussed in the session and I think @vanderaj agreed that it sounded like a sensible measure and since going forward the process will be in github this should be more transparent anyway.

**Comment by vanderaj** [comment]
We will be publishing our two new issues this coming Friday. Please follow along there.
