### ISSUE TITLE
A10 Feedback: include API-specific vulnerabilities in text - from Josh Grossman

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#61]
- A10 — Underprotected APIs: Agree with the idea but suggest that the accompanying text should be more focussed on API specific vulnerabilities such as Mass Assignment, CORS misconfig and JSONP.

**Comment by Neil-Smithline** [comment]
Based on the results of the industry survey ([background on survey](https://owasp.blogspot.com/2017/08/owasp-top-10-2017-project-update.html)), API vulnerabilities will not be in the Top-10. Where appropriate, mentions of API vulnerabilities will be added to other risks.
