### ISSUE TITLE
Feedback from Torsten Gigler

### ISSUE THREAD

**Issue by vanderaj** [OWASP/Top10#62]
Via google docs: Open

I've compiled all my comments now into the pptx file (I've send you the link to my google drive containing the previous draft, last week). (See Above)
I've read again all the Top 10 and gave a comment if I suggest to change some content. All changes ar highlighted by using green font and Comments (sometimes containing background information why I'd suggest a change). 

There might fit also:
•	a table of contents at the beginning (see comment on 'O', we've already added one athttps://www.owasp.org/images/4/42/OWASP_Top_10_2013_DE_Version_1_0.pdf) 
•	a new page '+A What's Nest for Application Managers' describing the lifecycle processes to tender a software, to implace the application  and its components, to maintain them, to change it, to retire it while keeping data for post production and finally to delete all data, software and components. (no comments added about this in thr pptx)
I'm sorry, I am not a native speaker, so I hope you can understand what I mean and there are not too much faults in my writing.

Please let me know, if you deeply disagree with some suggestions. If there aren't and you don't mind, I can send it also to the [owasp-topten] mailing list.

About deserialization, I've found two links: 
https://www.owasp.org/images/7/71/GOD16-Deserialization.pdf
https://www.owasp.org/index.php/Deserialization_Cheat_Sheet

I hope it helps for the discussions at the OWASP summit. I am sorry, I won't be there personally. If there are some electronic conversation channels we could try this, if you liked (or the days before the summit).

**Comment by sslHello** [comment]
Hi Andrew, you can close this issue:
It is identical to #12, details have been moved to individual issues #64 .. #79 by the page for all feedback that is in the pptx above (some were updated, too).
Besides the two points above in the text 'There might fit also...' -> #12

Cheers
Torsten (Gigler)

**Comment by sslHello** [comment]
It is identical to #12, details have been moved to individual issues #64 .. #79 by the page for all feedback that is in the pptx above (some were updated, too).
Besides the two points above in the text 'There might fit also...' -> #12

Cheers
Torsten
