### ISSUE TITLE
add Arabic language into  Official OWASP website.

### ISSUE THREAD

**Issue by Malajab** [OWASP/Top10#647]
Deas,

As you know we finally finished our translation for **Arabic** language, we need you help to upload it into official website.

thanks.

**Comment by Malajab** [comment]
Dears, 
Any Update...?

Thanks.

**Comment by sslHello** [comment]
Hi @Malajab,
This has been made by Andrew (@vanderaj) up to now.
I've fixed some issues in some languages. As mkdocs worked well locally I've rebuild the official pages right now.
As far as I see Arab works now, too :-).
Please let me know if you see any issues.

Cheers Torsten
