### ISSUE TITLE
OWASP Top 10 - 2017 RC1: A1 [Injection]

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#67]
I'd like to suggest minor edits,
 - [How Do I Prevent This?]
   - 2:  "If (1) is not available, you should normalize the input and carefully escape special characters using the specific escape syntax for that interpreter" (shortened, missing normalization could bypass (2) and (3)
 - [Example Attack Scenarios]
   - Scenario_1 : please change color to red and writing to bold 
   
The complete feedback is included in the PDF:
[OWASP Top 10 - 2017 RC1 Feedback Torsten_ A1-Injection.pdf](https://github.com/OWASP/Top10/files/1072395/OWASP.Top.10.-.2017.RC1.Feedback.Torsten_.A1-Injection.pdf)

Cheers 
Torsten Gigler

**Comment by sslHello** [comment]
Add references to #33, #25, #18

**Comment by Neil-Smithline** [comment]
Fixed in 108428fe0d9115ab0c2d0becf631e92f8cfb09f3
