### ISSUE TITLE
Ratio of time to gather/analyse data (Summit Process session, Mon AM1)

### ISSUE THREAD

**Issue by tghosth** [OWASP/Top10#7]
Does the ratio between time allocated to gathering data and time allocated to analysing the data make sense? 

For the 2017 list there was roughly 3 months for gathering data (~June - Aug) compared to roughly 7 months to analyse the data.

The full 2017 process was:
- 20 May 2016      - Initial call for data
- 31 July 2016     - Official deadline for submitting data (after an extension from 20 July).
(based on the data released, the last large submission was 31 August 2016).
- 17 December 2016 - Full data received released
- 10 April 2017    - Full RC1 released.
- 30 June 2017     - Proposed end to comment period
- July 2017        - Proposed final released

**Comment by tghosth** [comment]
This was briefly discussed in the session. For future Top 10s (2020, etc) it would presumably depend on what decision is taken on how the data will be analysed (e.g. will data scientists be used).

**Comment by vanderaj** [comment]
As we have re-opened the data call, closed the data call, received a lot more data, closed the call, analysed it, created a new ordering, I'm closing this issue.
