### ISSUE TITLE
zh_CN version of OWASP Top 10:2021 not displayed on https://owasp.org/Top10/

### ISSUE THREAD

**Issue by laozhoubuluo** [OWASP/Top10#702]
zh_CN version of OWASP Top 10:2021 not displayed on https://owasp.org/Top10/ , Consider refresh it to make zh_CN version can display.

**Comment by sslHello** [comment]
Hi @laozhoubuluo,
This has been made by Andrew (@vanderaj) up to now.
I've fixed some issues in some languages. As mkdocs worked well locally I've rebuild the official pages right now.

Cheers Torsten
