### ISSUE TITLE
OWASP Top 10 - 2017 RC1: A8 [Cross-Site Request Forgery (CSRF)]

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#73]
Feedback is included in the PDF:
[OWASP Top 10 - 2017 RC1 Feedback Torsten_ A8-Cross-Site Request Forgery_CSRF.pdf](https://github.com/OWASP/Top10/files/1072432/OWASP.Top.10.-.2017.RC1.Feedback.Torsten_.A8-Cross-Site.Request.Forgery_CSRF.pdf)

Cheers 
Torsten Gigler

**Comment by jmanico** [comment]
Torsten,

Please add comments directly vs posting a PDF, I state with respect.

--
Jim Manico
@Manicode

**Comment by sslHello** [comment]
Hi Jim,
sorry I've done all the review in thed pptx (see issue #12) . I've tried to to this, but it is is now too much work to extract it by the comment.
I'd loved to do it directly...
Cheers Torsten

**Comment by sslHello** [comment]
Finally I've copied the suggestions and comments from the PDFs to the issues, but this were hours of work... Directly from .pptx it did not work at all.

Cheers Torsten

**Comment by sslHello** [comment]
Add references to #38, #5

**Comment by vanderaj** [comment]
CSRF is out, so closing tickets.

**Comment by vanderaj** [comment]
CSRF is out, so closing tickets.
