### ISSUE TITLE
OWASP Top 10 - 2017 RC1: A10 [Underprotected APIs]

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#75]
I'd like to suggest to include 'deserialization' to A10, e.g. adding in 
[Am I Vulnerable to Attack?] 
Others use techniques like deserialization and get vulnerable by using this while being publically reachable.

Background: Applications using deserialization for publically reachable APIs get vulnerable (it does not matter if the Client App is provided or not).
I have no evidence to support this, but it seems that this vulnerability is more likely to show up in API communications than traditional web applications (e.g. used for parsing cookies).
Input validation seems NOT to completely mitigate the risk as bypassing ad-hoc SecurityManagers seems to be possible by design.
See e.g. https://www.owasp.org/images/7/71/GOD16-Deserialization.pdf
https://www.owasp.org/index.php/Deserialization_Cheat_Sheet

The complete feedback is included in the PDF:
[OWASP Top 10 - 2017 RC1 Feedback Torsten_ A10-Underprotected APIs.pdf](https://github.com/OWASP/Top10/files/1072460/OWASP.Top.10.-.2017.RC1.Feedback.Torsten_.A10-Underprotected.APIs.pdf)

Cheers 
Torsten Gigler

**Comment by sslHello** [comment]
Add references to #61, #58, #56, #46, #40, #39, #35, #29, #28, #4

**Comment by vanderaj** [comment]
This risk is going to be removed as per community feedback at the Project Summit, survey data and revised data call. Thank you for your input on this matter.
