### ISSUE TITLE
OWASP Top 10 - 2017 RC1: +D-What's Next for Developers

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#76]
I'd like to suggest, to add the [OWASP Juice Shop Project](https://www.owasp.org/index.php/OWASP_Juice_Shop_Project) to 'Application Security Education'.

The complete feedback is included in the PDF:
[OWASP Top 10 - 2017 RC1 Feedback Torsten_ +D-What_s Next for Developers.pdf](https://github.com/OWASP/Top10/files/1072449/OWASP.Top.10.-.2017.RC1.Feedback.Torsten_.D-What_s.Next.for.Developers.pdf)

Cheers 
Torsten Gigler

**Comment by sslHello** [comment]
Add reference to #51

**Comment by vanderaj** [comment]
@infosecdad I've resolved this issue. This will help free you up to get that data analysis section ready!
