### ISSUE TITLE
OWASP Top 10 - 2017 RC1: +F-Details About Risk Factors

### ISSUE THREAD

**Issue by sslHello** [OWASP/Top10#79]
I'd like to suggest,
 - [SummaryTable]: the graphical issue should be solved: a rectangle that interrupts the dots should be deleted
- A7 should be changed if it gets renamed
- to verity if 'For defenses, see: OWASP Deserialization Cheat Sheet' is still needed if it's integrated in A10; It might be still an issue if it is used for cookies, hidden variables etc (in common web applications)
- to add 'OWASP Top 10 Privacy Risks Project' at the very end: "User Privacy (CWE-359) For defenses, see: [OWASP Top 10 Privacy Risks Project](https://www.owasp.org/index.php/OWASP_Top_10_Privacy_Risks_Project)"

The complete feedback is included in the PDF:
[OWASP Top 10 - 2017 RC1 Feedback Torsten_ +F-Details About Risk Factors.pdf](https://github.com/OWASP/Top10/files/1072481/OWASP.Top.10.-.2017.RC1.Feedback.Torsten_.F-Details.About.Risk.Factors.pdf)

Cheers 
Torsten Gigler

**Comment by davewichers** [comment]
Add reference to: https://cwe.mitre.org/data/definitions/451.html for the Clickjacking risk listed under additional risks to consider.  (Although a direct CWE for Clickjacking would be better, but it doesn't exist).

**Comment by Neil-Smithline** [comment]
These also [https://capec.mitre.org/data/definitions/10 . html] (https://capec.mitre.org/data/definitions/10 . html).

**Comment by sslHello** [comment]
Add reference to #43

**Comment by vanderaj** [comment]
Whoops, I did this one. Please forgive me!
