### ISSUE TITLE
A5: Several modifications suggested

### ISSUE THREAD

**Issue by Neil-Smithline** [OWASP/Top10#80]
Talking about the example in the other three boxes it's a difficult to say so I'll go by exclusion. I wouldn't changed anything on "Am I Vulnerable to Attack?" or "How Do I Prevent This?" because IMO they are pretty solid and aligned with A5. And the item 5 under "Am I Vulnerable to Attack?" is already covering the security headers settings indirectly. So it needs to be some item from "Example Attack Scenarios".

The Scenario #4 under "Example Attack Scenarios" could be replaced since is talking about something that it's enabled by default and it should be removed. If you see Scenario #1 is about almost the same thing the only difference is instead of sample application is about admin console.

As you may have noticed I'm not a native English speaker so I'll put my suggestion for the possible new Scenario #4 below but most probably the English needs to be reviewed and updated.

Scenario #4 The app server do not send HSTS response header back to the user browser allowing a victim open connection in clear text (HTTP). A nearby attacker can possibly eavesdrop the connection stealing sensitive data or perform a MITM attack.

Ricardo Iramar dos Santos

**Comment by Calico90** [comment]
I think that Scenario #1 and #4 are slightly different indeed. Although generally #1 is more about default credentials and #4 is about sample applications. I think that the part "Automatically installed and not removed" should be removed in #1. Or Scenario #4 should be more specific.

**Comment by riramar** [comment]
When I was talking about these suggestion with Dave I also sent this comment below.

**_BTW the external reference "CIS Security Configuration Guides/Benchmarks" (http://benchmarks.cisecurity.org/downloads/benchmarks/) is broken. Maybe this should be pointed to https://www.cisecurity.org/cis-benchmarks/._**

Not sure if this was fixed.

**Comment by sslHello** [comment]
Hi Ricardo,
thank you very much for your comments.
I have split your suggestion into 2 parts:
- one detailed which fits very good to A6
- a more generalized meaning which is now in A5/Scenatio_5: "The default configuration or a copied old one activates old vulnerable protocol versions or options that can be misused by an attacker or malware.'
Issue resolved by the two updates mentioned above. Please review updated texts in A5 and A6.

**Comment by riramar** [comment]
Check and everything fine. :)
Thanks @sslHello !
