### ISSUE TITLE
A3 (XSS) - Prevention, link to Mozilla

### ISSUE THREAD

**Issue by einsweniger** [OWASP/Top10#83]
I'm not sure if I'm late to the party, since you already are at RC stage, but nevertheless:

I'd propose to link to Mozilla's [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) instead of the Wikipedia, as it is more in depth.
(The link in point 4 under prevention).

**Comment by Neil-Smithline** [comment]
Not late at all @einsweniger. There'll be another RC so there's plenty of time for commenting. Feel free to create more issues or comment on existing ones.

**Comment by Neil-Smithline** [comment]
Fixed in c36338442f93667a2bece74ffeed48cb41a3bde5
