### ISSUE TITLE
A4 [Broken Access Control] - "How do I prevent this?"

### ISSUE THREAD

**Issue by bchurchill** [OWASP/Top10#86]
Access control is often broken because it's not implemented consistently across an entire application.  It might be done correctly in one location, but incorrectly in another.  The trick to getting it right is to centralize the access control mechanism: we want to write the tricky logic once and reuse it everywhere.  This is important both for writing code correctly and for making it easy to audit later.  For example, one could write functions to check if the current user has permission to access a piece of functionality or a piece of data.

Therefore I recommend adding a point to the numbered list (perhaps between 2 and 3) that says something like,

> **Centralized Implementation**.  Implement access control mechanisms once and re-use them throughout the application.

If some text needs to be removed to make space, a line can be freed up by removing "to eliminate direct object references" from the end of the second list item.  Or replace "This coding pattern... resources" with something shorter (or remove it).

**Comment by sslHello** [comment]
@bchurchill - Thank you for your suggestion. Yes a centralized implementation is a good place.

Cheers Torsten
OWASP Top-10 Co-Leader

**Comment by Neil-Smithline** [comment]
Agree 100%. If we can find the space, I'd even be in favor adding something about implementing it in an implicit manner (eg: Servlet filters or other framework), than having explicit calls. Just too easy to miss a manual call to check access.

**Comment by jmanico** [comment]
This is called "The Principle of Least Mediation" where we want every
request checked for AuthN and AuthZ.

Aloha,

Jim
