### ISSUE TITLE
A3 [Cross-Site Scripting] - "How do I prevent XSS?"

### ISSUE THREAD

**Issue by bchurchill** [OWASP/Top10#87]
Recommendation:  Change

> **Consider** Content Security Policy (CSP) ...

to

> **Use** Content Security Policy (CSP) ...

The word "consider" comes with the connotation that maybe this is an advanced technique or not applicable in all cases.  However, I think the community believes it's ready for wide adoption.  In fact, in OWASP ASVS 3.0.1 the use of CSP is mandated for any project achieving even Level 1 (see 11.7).

**Comment by Neil-Smithline** [comment]
Good point. I'm sure that we can make the wording stronger.

**Comment by HoLyVieR** [comment]
While we are at it, I think we should change the second part of the sentence too. "to defend against XSS across your entire site" implicates that CSP is XSS prevention, when it's just mitigation. A wording like "to mitigate the impact of potential XSS across your entire site" would be more accurate.

**Comment by Neil-Smithline** [comment]
Both suggestions adopted in 3dc4d462243f5a2006ed685740e00623baef6b0c. Thanks for the input!
