### ISSUE TITLE
Update Wording of "Using Components with Known Vulnerabilities"

### ISSUE THREAD

**Issue by ossie-git** [OWASP/Top10#89]
I noticed that although the title is valid, it focuses solely on legitimate packages being vulnerable, and does not cover the use case where a developer mistakenly uses a backdoored or malicious component.  Examples of this include XcodeGhost (backdoored IDE) back in 2015 (https://nakedsecurity.sophos.com/2015/11/09/apples-xcodeghost-malware-still-in-the-machine/) and recently - https://duo.com/blog/hunting-malicious-npm-packages  I'm sure there are other cases and although the issue isn't currently critical, it would be a logical extension to this

Also, I think that you shouldn't just identity and monitor all components, but also to remove components that are not necessary.  It seems like a trivial thing to say, but it too is not explicitly mentioned here - https://www.owasp.org/index.php/Top_10_2013-A9-Using_Components_with_Known_Vulnerabilities  It just mentions either not relying on only 3rd party application and writing everything yourself (not likely) or using 3rd party applications and keeping them up-to-date.

**Comment by bchurchill** [comment]
These are great points.  Along these lines I would suggest adding something about preferring signed software from trustworthy sources.  That might partially address the concern about backdoored/malicious components.  My impression is that many projects don't have the resources to audit the source code or binary of a 3rd party component, but do have the resources to do some background research into its reputation and check for cryptographic signatures. This might fit in well with the 3rd list item.

If space is a concern when updating this document, I recommend removing the sentence "One option is not to use components you didn't write...".  In most cases, this isn't an option!

**Comment by ossie-git** [comment]
Verifying that all packages are signed is a good idea but I'm not sure if this is currently doable (I don't think npm packages are currently signed for example).  It's the right thing to do but I think it is a question of feasibility.  So perhaps it can be added as a suggestion when doable.

And your comment on removing the suggestion to write your own components is spot on.  Unless you have a strong team, a lot of time, and security experts (crypto PhDs, etc.), then writing your own libraries for everything is actually a bad idea in my opinion as you are more likely to shoot yourself in the foot.  99% or more of the OWASP Top 10 consumers probably don't have this a realistic option.

**Comment by bchurchill** [comment]
I actually made a mistake when I originally wrote the comment!  I was looking at the 2013 OWASP top 10 but that was already removed in the 2017 draft.

**Comment by Neil-Smithline** [comment]
I've added this to the "how do i prevent" section. 
> * Only obtain your components from official sources and, when possible, prefer signed packages to reduce the chance of getting a modified, malicious component. 

Thanks for the suggestions!

**Comment by Neil-Smithline** [comment]
Regarding the statement about removing unneeded components, the text already states:
> * Analyze libraries to be sure they are actually invoked at runtime before making changes, as many components are never loaded or invoked.

Are you looking for something more?

**Comment by vanderaj** [comment]
I've reworded that point to be closer to the original suggestion, and put it at the top, and I'm closing out this issue.
