### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by drkknight** [OWASP/Top10#93]
I honestly believe one of the TOP 10 should be logging.  As security analysts, we always look at logs to determine where an attack may have occurred.  In web application development, there are sooo many interactions that could happen and if appropriate logging was occurring, it might assist both developers and security teams in finding flaws.

**Comment by sslHello** [comment]
@drkknight if you haven't already, we'd appreciate you taking the survey. That's the best place to register you're opinions on what's most important. https://docs.google.com/forms/d/e/1FAIpQLSdy-ok2o_BBHsZn0r5WfwxOkCv1CQ4nKZ8VSmD6bYq-du22hg/viewform
Insufficient Logging and Monitoring [CWE-223 / CWE-778] is included in the list.
The deadline for the survey is 18 September, 2017.

**Comment by vanderaj** [comment]
The data call is now over, and we have received over 500 submissions on what should be included. This issue will be closed, as the method of selecting new items for the OWASP Top 10 is derived from the survey. Please hang in there, I think you'll be happy with where we and the community landed on this topic.
