### ISSUE TITLE
A2: fine tuning the authentication section

### ISSUE THREAD

**Issue by drwetter** [OWASP/Top10#99]
In **Am I vulnerable to attack?**

is currently
``` 
Common authentication vulnerabilities include:

  *  missing multi-factor authentication, such as TOTP, token, or risk based authentication
  *  permits credential stuffing, which is where the attacker has a list of valid usernames and passwords. Applications should monitor and block many login attempts
  *  permits brute force attacks against default and well known passwords
  *  permits weak or well known passwords, such as "Password1" or "admin/admin"
  *  weak or ineffectual credential recovery and forgot password processes, such as "knowledge-based answers", which cannot be made safe
   * plain text, encrypted, or weakly hashed passwords permit the rapid recovery of passwords using GPU crackers or brute force tools
```

As noted in #68 I would not make it mandatory to use 2FA (first point). This seems more appropriate in ``How do I prevent``. 

The following point ``permits credential stuffing,`` and ``permits brute force attacks``  could be rephrased to ``permits brute force or other automated attacks`` but could be as well put to the ``How do I prevent`` section -- depends on space and how this is being sold. Is it really a vulnerability or an additional protection?

 ``permits weak or well known passwords, such as "Password1" or "admin/admin"`` can be shortened (but must not necessarily) to ``allows weak pw policy``

``Password recovery tools allow the rapid recovery of plain text, encrypted, or weakly hashed passwords in case of password hash disclosure``

Shorter: ``failed to encrypt stored passwords properly (no salts and/or weak hashes/encryption)``

This I would put as a first point -- the order has a significance.

**Comment by vanderaj** [comment]
Thanks Dirk, I've addressed most of this. Realistically, I am pushing for MFA. It's in NIST 800-63, and it's time to stop letting folks get away with usernames + passwords. Lack of MFA as an option for all apps is a clear and present danger to the Internet. It's time. 

Andrew
